apiVersion: v1
kind: Secret
metadata:
  name: durable-workflow-env
  namespace: durable-workflow
  labels:
    app.kubernetes.io/name: durable-workflow
type: Opaque
stringData:
  APP_NAME: "Durable Workflow Server"
  APP_ENV: production
  APP_KEY: "base64:CHANGE_ME"
  APP_DEBUG: "false"
  DB_CONNECTION: mysql
  DB_HOST: mysql.durable-workflow.svc.cluster.local
  DB_PORT: "3306"
  DB_DATABASE: durable_workflow
  DB_USERNAME: workflow
  DB_PASSWORD: "CHANGE_ME"
  REDIS_HOST: redis.durable-workflow.svc.cluster.local
  QUEUE_CONNECTION: redis
  CACHE_STORE: redis
  WORKFLOW_SERVER_AUTH_DRIVER: token
  WORKFLOW_SERVER_AUTH_TOKEN: "CHANGE_ME"
  WORKFLOW_SERVER_WORKER_TOKEN: "CHANGE_ME_WORKER"
  WORKFLOW_SERVER_OPERATOR_TOKEN: "CHANGE_ME_OPERATOR"
  WORKFLOW_SERVER_ADMIN_TOKEN: "CHANGE_ME_ADMIN"
  WORKFLOW_SERVER_AUTH_BACKWARD_COMPATIBLE: "true"
