-- Frozen published PHP physical schema; no rows or live next-ID counters.
SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE IF NOT EXISTS `activity_attempts` (
  `id` varchar(26) NOT NULL,
  `workflow_run_id` varchar(26) NOT NULL,
  `activity_execution_id` varchar(26) NOT NULL,
  `workflow_task_id` varchar(26) DEFAULT NULL,
  `worker_attempt_id` varchar(255) DEFAULT NULL,
  `attempt_number` int(10) unsigned NOT NULL,
  `status` varchar(255) NOT NULL,
  `lease_owner` varchar(255) DEFAULT NULL,
  `started_at` timestamp(6) NOT NULL,
  `last_heartbeat_at` timestamp(6) NULL DEFAULT NULL,
  `lease_expires_at` timestamp(6) NULL DEFAULT NULL,
  `closed_at` timestamp(6) NULL DEFAULT NULL,
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `activity_attempts_activity_execution_id_attempt_number_unique` (`activity_execution_id`,`attempt_number`),
  KEY `activity_attempts_workflow_run_id_index` (`workflow_run_id`),
  KEY `activity_attempts_activity_execution_id_index` (`activity_execution_id`),
  KEY `activity_attempts_workflow_task_id_index` (`workflow_task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `activity_executions` (
  `id` varchar(26) NOT NULL,
  `workflow_run_id` varchar(26) NOT NULL,
  `sequence` int(10) unsigned NOT NULL,
  `activity_class` varchar(255) NOT NULL,
  `activity_type` varchar(255) NOT NULL,
  `status` varchar(255) NOT NULL,
  `payload_codec` varchar(255) DEFAULT NULL,
  `arguments` longtext DEFAULT NULL,
  `result` longtext DEFAULT NULL,
  `exception` longtext DEFAULT NULL,
  `connection` varchar(255) DEFAULT NULL,
  `queue` varchar(255) DEFAULT NULL,
  `attempt_count` int(10) unsigned NOT NULL DEFAULT 1,
  `current_attempt_id` varchar(26) DEFAULT NULL,
  `retry_policy` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`retry_policy`)),
  `parallel_group_path` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`parallel_group_path`)),
  `activity_options` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`activity_options`)),
  `schedule_deadline_at` timestamp(6) NULL DEFAULT NULL,
  `close_deadline_at` timestamp(6) NULL DEFAULT NULL,
  `schedule_to_close_deadline_at` timestamp(6) NULL DEFAULT NULL,
  `heartbeat_deadline_at` timestamp(6) NULL DEFAULT NULL,
  `started_at` timestamp(6) NULL DEFAULT NULL,
  `closed_at` timestamp(6) NULL DEFAULT NULL,
  `last_heartbeat_at` timestamp(6) NULL DEFAULT NULL,
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `activity_executions_workflow_run_id_sequence_unique` (`workflow_run_id`,`sequence`),
  KEY `activity_executions_workflow_run_id_index` (`workflow_run_id`),
  KEY `activity_exec_prom_metrics_series_idx` (`workflow_run_id`,`queue`,`activity_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `failed_jobs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) NOT NULL,
  `connection` text NOT NULL,
  `queue` text NOT NULL,
  `payload` longtext NOT NULL,
  `exception` longtext NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `jobs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `queue` varchar(255) NOT NULL,
  `payload` longtext NOT NULL,
  `attempts` tinyint(3) unsigned NOT NULL,
  `reserved_at` int(10) unsigned DEFAULT NULL,
  `available_at` int(10) unsigned NOT NULL,
  `created_at` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `jobs_queue_index` (`queue`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `migrations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) NOT NULL,
  `batch` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `runtime_credentials` (
  `id` varchar(64) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `subject` varchar(255) NOT NULL,
  `roles` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`roles`)),
  `tenant` varchar(128) NOT NULL,
  `claims` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`claims`)),
  `token_prefix` varchar(16) NOT NULL,
  `token_hash` char(64) NOT NULL,
  `expires_at` timestamp NULL DEFAULT NULL,
  `revoked_at` timestamp NULL DEFAULT NULL,
  `rotated_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `runtime_credentials_token_hash_unique` (`token_hash`),
  KEY `runtime_credentials_tenant_index` (`tenant`),
  KEY `runtime_credentials_expires_at_index` (`expires_at`),
  KEY `runtime_credentials_revoked_at_index` (`revoked_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `runtime_external_payloads` (
  `id` varchar(64) NOT NULL,
  `namespace` varchar(128) NOT NULL,
  `storage_uri` text NOT NULL,
  `storage_uri_sha256` char(64) NOT NULL,
  `codec` varchar(64) NOT NULL,
  `sha256` char(64) NOT NULL,
  `size_bytes` bigint(20) unsigned NOT NULL,
  `upload_status` varchar(16) NOT NULL DEFAULT 'ready',
  `retained_at` timestamp NULL DEFAULT NULL,
  `expires_at` timestamp NULL DEFAULT NULL,
  `last_fetched_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `runtime_external_payloads_namespace_uri_unique` (`namespace`,`storage_uri_sha256`),
  KEY `runtime_external_payloads_namespace_index` (`namespace`),
  KEY `runtime_external_payloads_expires_at_index` (`expires_at`),
  KEY `runtime_external_payloads_reclamation_idx` (`retained_at`,`expires_at`,`upload_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `runtime_external_payload_backup_hold` (
  `id` tinyint(3) unsigned NOT NULL,
  `owner` char(36) DEFAULT NULL,
  `acquired_at` timestamp NULL DEFAULT NULL,
  `expires_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `runtime_external_payload_cleanup_stats` (
  `namespace` varchar(128) NOT NULL,
  `passes_total` bigint(20) unsigned NOT NULL DEFAULT 0,
  `deleted_references_total` bigint(20) unsigned NOT NULL DEFAULT 0,
  `deleted_backing_objects_total` bigint(20) unsigned NOT NULL DEFAULT 0,
  `shared_objects_preserved_total` bigint(20) unsigned NOT NULL DEFAULT 0,
  `blocked_outcomes_total` bigint(20) unsigned NOT NULL DEFAULT 0,
  `storage_driver_failures_total` bigint(20) unsigned NOT NULL DEFAULT 0,
  `last_processed` int(10) unsigned NOT NULL DEFAULT 0,
  `last_deleted_references` int(10) unsigned NOT NULL DEFAULT 0,
  `last_deleted_backing_objects` int(10) unsigned NOT NULL DEFAULT 0,
  `last_shared_objects_preserved` int(10) unsigned NOT NULL DEFAULT 0,
  `last_blocked_outcomes` int(10) unsigned NOT NULL DEFAULT 0,
  `last_storage_driver_failures` int(10) unsigned NOT NULL DEFAULT 0,
  `last_pass_status` varchar(16) DEFAULT NULL,
  `last_completed_at` timestamp NULL DEFAULT NULL,
  `last_storage_failure_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`namespace`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `runtime_external_payload_object_locks` (
  `bucket` smallint(5) unsigned NOT NULL,
  PRIMARY KEY (`bucket`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `runtime_payload_completion_budgets` (
  `id` char(64) NOT NULL,
  `namespace` varchar(128) NOT NULL,
  `context` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`context`)),
  `slots` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`slots`)),
  `objects` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`objects`)),
  `expires_at` timestamp NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `runtime_payload_completion_budgets_namespace_index` (`namespace`),
  KEY `runtime_payload_completion_budgets_expires_at_index` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `search_attribute_definitions` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `namespace` varchar(128) NOT NULL,
  `name` varchar(128) NOT NULL,
  `type` varchar(32) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `search_attribute_definitions_namespace_name_unique` (`namespace`,`name`),
  KEY `search_attribute_definitions_namespace_index` (`namespace`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_child_calls` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `parent_workflow_run_id` varchar(26) NOT NULL,
  `parent_workflow_instance_id` varchar(191) NOT NULL,
  `sequence` int(10) unsigned NOT NULL,
  `child_workflow_type` varchar(191) NOT NULL,
  `child_workflow_class` varchar(255) NOT NULL,
  `requested_child_id` varchar(191) DEFAULT NULL,
  `resolved_child_instance_id` varchar(191) DEFAULT NULL,
  `resolved_child_run_id` varchar(26) DEFAULT NULL,
  `parent_close_policy` varchar(32) NOT NULL DEFAULT 'abandon',
  `connection` varchar(191) DEFAULT NULL,
  `queue` varchar(191) DEFAULT NULL,
  `compatibility` varchar(191) DEFAULT NULL,
  `retry_policy` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`retry_policy`)),
  `timeout_policy` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`timeout_policy`)),
  `cancellation_propagation` tinyint(1) NOT NULL DEFAULT 0,
  `status` varchar(32) NOT NULL DEFAULT 'scheduled',
  `result_payload_reference` varchar(191) DEFAULT NULL,
  `failure_reference` varchar(191) DEFAULT NULL,
  `closed_reason` varchar(64) DEFAULT NULL,
  `scheduled_at` timestamp(6) NOT NULL,
  `started_at` timestamp(6) NULL DEFAULT NULL,
  `closed_at` timestamp(6) NULL DEFAULT NULL,
  `arguments` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`arguments`)),
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `child_calls_parent_seq` (`parent_workflow_run_id`,`sequence`),
  KEY `child_calls_parent_status` (`parent_workflow_run_id`,`status`),
  KEY `child_calls_child_parent` (`resolved_child_instance_id`,`parent_workflow_run_id`),
  KEY `workflow_child_calls_parent_workflow_run_id_index` (`parent_workflow_run_id`),
  KEY `workflow_child_calls_parent_workflow_instance_id_index` (`parent_workflow_instance_id`),
  KEY `workflow_child_calls_sequence_index` (`sequence`),
  KEY `workflow_child_calls_resolved_child_instance_id_index` (`resolved_child_instance_id`),
  KEY `workflow_child_calls_resolved_child_run_id_index` (`resolved_child_run_id`),
  KEY `workflow_child_calls_status_index` (`status`),
  CONSTRAINT `workflow_child_calls_parent_workflow_run_id_foreign` FOREIGN KEY (`parent_workflow_run_id`) REFERENCES `workflow_runs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_child_projection_repairs` (
  `workflow_history_event_id` varchar(26) NOT NULL,
  `workflow_run_id` varchar(26) NOT NULL,
  `workflow_task_id` varchar(26) NOT NULL,
  `history_sequence` int(10) unsigned NOT NULL,
  `failure_id` varchar(26) DEFAULT NULL,
  `failed_child_counted_at` timestamp(6) NULL DEFAULT NULL,
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`workflow_history_event_id`),
  KEY `workflow_child_projection_repairs_drain_idx` (`workflow_run_id`,`workflow_task_id`,`history_sequence`),
  KEY `workflow_child_projection_repairs_failure_idx` (`workflow_run_id`,`failure_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_commands` (
  `id` varchar(26) NOT NULL,
  `workflow_instance_id` varchar(191) DEFAULT NULL,
  `workflow_run_id` varchar(26) DEFAULT NULL,
  `requested_workflow_run_id` varchar(26) DEFAULT NULL,
  `resolved_workflow_run_id` varchar(26) DEFAULT NULL,
  `command_type` varchar(255) NOT NULL,
  `target_scope` varchar(255) NOT NULL DEFAULT 'instance',
  `source` varchar(255) NOT NULL DEFAULT 'php',
  `context` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`context`)),
  `request_id` varchar(191) DEFAULT NULL,
  `status` varchar(255) NOT NULL,
  `outcome` varchar(255) DEFAULT NULL,
  `workflow_class` varchar(255) DEFAULT NULL,
  `workflow_type` varchar(255) DEFAULT NULL,
  `payload_codec` varchar(255) DEFAULT NULL,
  `payload` longtext DEFAULT NULL,
  `rejection_reason` varchar(255) DEFAULT NULL,
  `command_sequence` int(10) unsigned DEFAULT NULL,
  `message_sequence` int(10) unsigned DEFAULT NULL,
  `accepted_at` timestamp(6) NULL DEFAULT NULL,
  `applied_at` timestamp(6) NULL DEFAULT NULL,
  `rejected_at` timestamp(6) NULL DEFAULT NULL,
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `workflow_commands_request_lookup` (`workflow_instance_id`,`command_type`,`request_id`),
  KEY `workflow_commands_workflow_instance_id_index` (`workflow_instance_id`),
  KEY `workflow_commands_workflow_run_id_index` (`workflow_run_id`),
  KEY `workflow_commands_requested_workflow_run_id_index` (`requested_workflow_run_id`),
  KEY `workflow_commands_resolved_workflow_run_id_index` (`resolved_workflow_run_id`),
  KEY `workflow_commands_command_type_index` (`command_type`),
  KEY `workflow_commands_source_index` (`source`),
  KEY `workflow_commands_status_index` (`status`),
  KEY `workflow_commands_command_sequence_index` (`command_sequence`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_durable_streams` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `namespace` varchar(128) NOT NULL,
  `workflow_instance_id` varchar(191) NOT NULL,
  `workflow_run_id` varchar(26) NOT NULL,
  `stream_name` varchar(191) NOT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'open',
  `last_offset` bigint(20) NOT NULL DEFAULT -1,
  `total_items` bigint(20) unsigned NOT NULL DEFAULT 0,
  `retention_seconds` int(10) unsigned DEFAULT NULL,
  `opened_at` timestamp(6) NULL DEFAULT NULL,
  `last_appended_at` timestamp(6) NULL DEFAULT NULL,
  `closed_at` timestamp(6) NULL DEFAULT NULL,
  `error_reason` varchar(191) DEFAULT NULL,
  `pending_items` bigint(20) unsigned NOT NULL DEFAULT 0,
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `wf_durable_streams_run_name_unique` (`workflow_run_id`,`stream_name`),
  KEY `wf_durable_streams_ns_instance_name_idx` (`namespace`,`workflow_instance_id`,`stream_name`),
  KEY `wf_durable_streams_ns_status_idx` (`namespace`,`status`),
  KEY `workflow_durable_streams_namespace_index` (`namespace`),
  KEY `workflow_durable_streams_workflow_instance_id_index` (`workflow_instance_id`),
  KEY `workflow_durable_streams_workflow_run_id_index` (`workflow_run_id`),
  KEY `workflow_durable_streams_status_index` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_durable_stream_items` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `stream_id` bigint(20) unsigned NOT NULL,
  `namespace` varchar(128) NOT NULL,
  `workflow_run_id` varchar(26) NOT NULL,
  `stream_name` varchar(191) NOT NULL,
  `offset` bigint(20) NOT NULL,
  `idempotency_key` varchar(191) DEFAULT NULL,
  `origin` varchar(64) NOT NULL DEFAULT 'workflow_command',
  `origin_reference` varchar(191) DEFAULT NULL,
  `payload` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`payload`)),
  `payload_reference` varchar(191) DEFAULT NULL,
  `payload_codec` varchar(64) DEFAULT NULL,
  `item_type` varchar(64) DEFAULT NULL,
  `content_type` varchar(191) DEFAULT NULL,
  `emitted_at` timestamp(6) NOT NULL,
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `wf_durable_stream_items_stream_offset_unique` (`stream_id`,`offset`),
  UNIQUE KEY `wf_durable_stream_items_idempotency_unique` (`stream_id`,`idempotency_key`),
  KEY `wf_durable_stream_items_run_name_offset_idx` (`workflow_run_id`,`stream_name`,`offset`),
  KEY `workflow_durable_stream_items_namespace_index` (`namespace`),
  KEY `workflow_durable_stream_items_workflow_run_id_index` (`workflow_run_id`),
  CONSTRAINT `workflow_durable_stream_items_stream_id_foreign` FOREIGN KEY (`stream_id`) REFERENCES `workflow_durable_streams` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_failures` (
  `id` varchar(26) NOT NULL,
  `workflow_run_id` varchar(26) NOT NULL,
  `source_kind` varchar(255) NOT NULL,
  `source_id` varchar(255) NOT NULL,
  `propagation_kind` varchar(255) NOT NULL,
  `failure_category` varchar(255) DEFAULT NULL,
  `non_retryable` tinyint(1) NOT NULL DEFAULT 0,
  `handled` tinyint(1) NOT NULL DEFAULT 0,
  `exception_class` varchar(255) NOT NULL,
  `message` text NOT NULL,
  `file` text NOT NULL,
  `line` int(10) unsigned DEFAULT NULL,
  `trace_preview` longtext DEFAULT NULL,
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `workflow_failures_source_kind_source_id_index` (`source_kind`,`source_id`),
  KEY `workflow_failures_workflow_run_id_index` (`workflow_run_id`),
  KEY `workflow_failures_failure_category_index` (`failure_category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_history_events` (
  `id` varchar(26) NOT NULL,
  `workflow_run_id` varchar(26) NOT NULL,
  `sequence` int(10) unsigned NOT NULL,
  `event_type` varchar(255) NOT NULL,
  `payload` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`payload`)),
  `workflow_task_id` varchar(26) DEFAULT NULL,
  `workflow_command_id` varchar(26) DEFAULT NULL,
  `recorded_at` timestamp(6) NULL DEFAULT NULL,
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  `recorded_at_utc` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `workflow_history_events_workflow_run_id_sequence_unique` (`workflow_run_id`,`sequence`),
  KEY `workflow_history_events_workflow_run_id_index` (`workflow_run_id`),
  KEY `workflow_history_events_workflow_task_id_index` (`workflow_task_id`),
  KEY `workflow_history_events_workflow_command_id_index` (`workflow_command_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_inbound_streams` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `namespace` varchar(128) NOT NULL,
  `workflow_instance_id` varchar(191) NOT NULL,
  `stream_name` varchar(128) NOT NULL,
  `last_position` bigint(20) unsigned NOT NULL DEFAULT 0,
  `cursor_position` bigint(20) unsigned NOT NULL DEFAULT 0,
  `cursor_checkpoint_run_id` varchar(26) DEFAULT NULL,
  `waiting_run_id` varchar(26) DEFAULT NULL,
  `waiting_after_position` bigint(20) unsigned DEFAULT NULL,
  `waiting_since` timestamp(6) NULL DEFAULT NULL,
  `duplicate_count` bigint(20) unsigned NOT NULL DEFAULT 0,
  `malformed_count` bigint(20) unsigned NOT NULL DEFAULT 0,
  `last_input_outcome` varchar(64) DEFAULT NULL,
  `last_input_message_id` varchar(191) DEFAULT NULL,
  `last_input_at` timestamp(6) NULL DEFAULT NULL,
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  `cleanup_blocked_at` timestamp(6) NULL DEFAULT NULL,
  `cleanup_blocked_reason` varchar(64) DEFAULT NULL,
  `cleanup_blocked_run_id` varchar(26) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `wf_inbound_streams_ns_instance_name_unique` (`namespace`,`workflow_instance_id`,`stream_name`),
  KEY `workflow_inbound_streams_namespace_index` (`namespace`),
  KEY `workflow_inbound_streams_workflow_instance_id_index` (`workflow_instance_id`),
  KEY `workflow_inbound_streams_cursor_checkpoint_run_id_index` (`cursor_checkpoint_run_id`),
  KEY `workflow_inbound_streams_waiting_run_id_index` (`waiting_run_id`),
  KEY `workflow_inbound_streams_cleanup_blocked_run_id_index` (`cleanup_blocked_run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_inbound_stream_items` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `stream_id` bigint(20) unsigned NOT NULL,
  `namespace` varchar(128) NOT NULL,
  `workflow_instance_id` varchar(191) NOT NULL,
  `stream_name` varchar(128) NOT NULL,
  `message_id` varchar(191) NOT NULL,
  `position` bigint(20) unsigned NOT NULL,
  `payload_codec` varchar(32) NOT NULL,
  `payload_blob` longtext NOT NULL,
  `payload_hash` varchar(64) NOT NULL,
  `delivered_run_id` varchar(26) DEFAULT NULL,
  `workflow_command_id` varchar(26) DEFAULT NULL,
  `delivered_at` timestamp(6) NULL DEFAULT NULL,
  `consumed_run_id` varchar(26) DEFAULT NULL,
  `consumed_task_id` varchar(26) DEFAULT NULL,
  `consumed_at` timestamp(6) NULL DEFAULT NULL,
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  `payload_released_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `wf_inbound_items_stream_message_unique` (`stream_id`,`message_id`),
  UNIQUE KEY `wf_inbound_items_stream_position_unique` (`stream_id`,`position`),
  KEY `wf_inbound_items_ns_instance_name_position_idx` (`namespace`,`workflow_instance_id`,`stream_name`,`position`),
  KEY `workflow_inbound_stream_items_namespace_index` (`namespace`),
  KEY `workflow_inbound_stream_items_workflow_instance_id_index` (`workflow_instance_id`),
  KEY `workflow_inbound_stream_items_delivered_run_id_index` (`delivered_run_id`),
  KEY `workflow_inbound_stream_items_workflow_command_id_index` (`workflow_command_id`),
  KEY `workflow_inbound_stream_items_consumed_run_id_index` (`consumed_run_id`),
  KEY `workflow_inbound_stream_items_consumed_task_id_index` (`consumed_task_id`),
  KEY `workflow_inbound_stream_items_payload_released_at_index` (`payload_released_at`),
  CONSTRAINT `workflow_inbound_stream_items_stream_id_foreign` FOREIGN KEY (`stream_id`) REFERENCES `workflow_inbound_streams` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_instances` (
  `id` varchar(191) NOT NULL,
  `workflow_class` varchar(255) NOT NULL,
  `workflow_type` varchar(255) NOT NULL,
  `namespace` varchar(255) DEFAULT NULL,
  `business_key` varchar(191) DEFAULT NULL,
  `visibility_labels` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`visibility_labels`)),
  `memo` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`memo`)),
  `execution_timeout_seconds` int(10) unsigned DEFAULT NULL,
  `current_run_id` varchar(26) DEFAULT NULL,
  `run_count` int(10) unsigned NOT NULL DEFAULT 0,
  `last_message_sequence` int(10) unsigned NOT NULL DEFAULT 0,
  `reserved_at` timestamp(6) NULL DEFAULT NULL,
  `started_at` timestamp(6) NULL DEFAULT NULL,
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `workflow_instances_namespace_index` (`namespace`),
  KEY `workflow_instances_business_key_index` (`business_key`),
  KEY `workflow_instances_current_run_id_index` (`current_run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_links` (
  `id` varchar(26) NOT NULL,
  `link_type` varchar(255) NOT NULL,
  `sequence` int(10) unsigned DEFAULT NULL,
  `parallel_group_path` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`parallel_group_path`)),
  `parent_workflow_instance_id` varchar(191) NOT NULL,
  `parent_workflow_run_id` varchar(26) NOT NULL,
  `child_workflow_instance_id` varchar(191) NOT NULL,
  `child_workflow_run_id` varchar(26) NOT NULL,
  `is_primary_parent` tinyint(1) NOT NULL DEFAULT 0,
  `parent_close_policy` varchar(255) NOT NULL DEFAULT 'abandon',
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `workflow_links_parent_child_type_unique` (`parent_workflow_run_id`,`child_workflow_run_id`,`link_type`),
  KEY `workflow_links_parent_sequence_type_index` (`parent_workflow_run_id`,`sequence`,`link_type`),
  KEY `workflow_links_parent_workflow_instance_id_index` (`parent_workflow_instance_id`),
  KEY `workflow_links_parent_workflow_run_id_index` (`parent_workflow_run_id`),
  KEY `workflow_links_child_workflow_instance_id_index` (`child_workflow_instance_id`),
  KEY `workflow_links_child_workflow_run_id_index` (`child_workflow_run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_memos` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `workflow_run_id` varchar(26) NOT NULL,
  `workflow_instance_id` varchar(191) NOT NULL,
  `key` varchar(191) NOT NULL,
  `value` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`value`)),
  `upserted_at_sequence` int(10) unsigned NOT NULL,
  `inherited_from_parent` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  `portable_value` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`portable_value`)),
  `portable_value_sequence` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `workflow_memos_run_key_unique` (`workflow_run_id`,`key`),
  KEY `workflow_memos_instance_key` (`workflow_instance_id`,`key`),
  CONSTRAINT `workflow_memos_workflow_run_id_foreign` FOREIGN KEY (`workflow_run_id`) REFERENCES `workflow_runs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_messages` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `workflow_instance_id` varchar(191) NOT NULL,
  `workflow_run_id` varchar(26) DEFAULT NULL,
  `direction` varchar(16) NOT NULL,
  `channel` varchar(64) NOT NULL,
  `stream_key` varchar(191) NOT NULL,
  `sequence` bigint(20) unsigned NOT NULL,
  `source_workflow_instance_id` varchar(191) DEFAULT NULL,
  `source_workflow_run_id` varchar(26) DEFAULT NULL,
  `target_workflow_instance_id` varchar(191) DEFAULT NULL,
  `target_workflow_run_id` varchar(26) DEFAULT NULL,
  `correlation_id` varchar(191) DEFAULT NULL,
  `idempotency_key` varchar(191) DEFAULT NULL,
  `payload_reference` varchar(191) DEFAULT NULL,
  `consume_state` varchar(16) NOT NULL DEFAULT 'pending',
  `consumed_at` timestamp(6) NULL DEFAULT NULL,
  `consumed_by_sequence` int(10) unsigned DEFAULT NULL,
  `expires_at` timestamp(6) NULL DEFAULT NULL,
  `delivery_attempt_count` int(10) unsigned NOT NULL DEFAULT 0,
  `last_delivery_attempt_at` timestamp(6) NULL DEFAULT NULL,
  `last_delivery_error` text DEFAULT NULL,
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `wf_msgs_stream_seq_unique` (`workflow_instance_id`,`stream_key`,`sequence`),
  KEY `wf_msgs_instance_stream_seq` (`workflow_instance_id`,`stream_key`,`sequence`),
  KEY `wf_msgs_run_dir_state` (`workflow_run_id`,`direction`,`consume_state`),
  KEY `wf_msgs_stream_seq_state` (`stream_key`,`sequence`,`consume_state`),
  KEY `wf_msgs_target_state` (`target_workflow_instance_id`,`consume_state`),
  KEY `workflow_messages_workflow_instance_id_index` (`workflow_instance_id`),
  KEY `workflow_messages_workflow_run_id_index` (`workflow_run_id`),
  KEY `workflow_messages_direction_index` (`direction`),
  KEY `workflow_messages_channel_index` (`channel`),
  KEY `workflow_messages_stream_key_index` (`stream_key`),
  KEY `workflow_messages_sequence_index` (`sequence`),
  KEY `workflow_messages_source_workflow_instance_id_index` (`source_workflow_instance_id`),
  KEY `workflow_messages_target_workflow_instance_id_index` (`target_workflow_instance_id`),
  KEY `workflow_messages_correlation_id_index` (`correlation_id`),
  KEY `workflow_messages_idempotency_key_index` (`idempotency_key`),
  KEY `workflow_messages_consume_state_index` (`consume_state`),
  CONSTRAINT `workflow_messages_workflow_run_id_foreign` FOREIGN KEY (`workflow_run_id`) REFERENCES `workflow_runs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_namespaces` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(128) NOT NULL,
  `description` varchar(1000) DEFAULT NULL,
  `retention_mode` varchar(32) NOT NULL DEFAULT 'bounded',
  `retention_days` int(10) unsigned DEFAULT 30,
  `status` varchar(32) NOT NULL DEFAULT 'active',
  `external_payload_storage` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`external_payload_storage`)),
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `workflow_namespaces_name_unique` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_runs` (
  `id` varchar(26) NOT NULL,
  `workflow_instance_id` varchar(191) NOT NULL,
  `run_number` int(10) unsigned NOT NULL,
  `workflow_class` varchar(255) NOT NULL,
  `workflow_type` varchar(255) NOT NULL,
  `namespace` varchar(255) DEFAULT NULL,
  `business_key` varchar(191) DEFAULT NULL,
  `visibility_labels` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`visibility_labels`)),
  `status` varchar(255) NOT NULL,
  `closed_reason` varchar(255) DEFAULT NULL,
  `compatibility` varchar(255) DEFAULT NULL,
  `payload_codec` varchar(255) DEFAULT NULL,
  `arguments` longtext DEFAULT NULL,
  `output` longtext DEFAULT NULL,
  `output_payload_codec` varchar(255) DEFAULT NULL,
  `connection` varchar(255) DEFAULT NULL,
  `queue` varchar(255) DEFAULT NULL,
  `priority` tinyint(3) unsigned NOT NULL DEFAULT 5,
  `fairness_key` varchar(64) DEFAULT NULL,
  `fairness_weight` smallint(5) unsigned NOT NULL DEFAULT 1,
  `sticky_worker_id` varchar(255) DEFAULT NULL,
  `sticky_until` timestamp(6) NULL DEFAULT NULL,
  `last_history_sequence` int(10) unsigned NOT NULL DEFAULT 0,
  `last_command_sequence` int(10) unsigned NOT NULL DEFAULT 0,
  `message_cursor_position` int(10) unsigned NOT NULL DEFAULT 0,
  `run_timeout_seconds` int(10) unsigned DEFAULT NULL,
  `execution_deadline_at` timestamp(6) NULL DEFAULT NULL,
  `run_deadline_at` timestamp(6) NULL DEFAULT NULL,
  `started_at` timestamp(6) NULL DEFAULT NULL,
  `closed_at` timestamp(6) NULL DEFAULT NULL,
  `archived_at` timestamp(6) NULL DEFAULT NULL,
  `archive_command_id` varchar(26) DEFAULT NULL,
  `archive_reason` varchar(255) DEFAULT NULL,
  `last_progress_at` timestamp(6) NULL DEFAULT NULL,
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  `import_source` varchar(64) DEFAULT NULL,
  `import_id` varchar(64) DEFAULT NULL,
  `import_dedupe_key` varchar(191) DEFAULT NULL,
  `import_contract_version` smallint(5) unsigned DEFAULT NULL,
  `imported_at` timestamp(6) NULL DEFAULT NULL,
  `cancellation_request_command_id` varchar(26) DEFAULT NULL,
  `cancellation_requested_at` timestamp(6) NULL DEFAULT NULL,
  `cancellation_deadline_at` timestamp(6) NULL DEFAULT NULL,
  `cancellation_delivery_sequence` int(10) unsigned DEFAULT NULL,
  `cancellation_delivered_at` timestamp(6) NULL DEFAULT NULL,
  `details_pruned_at` timestamp(6) NULL DEFAULT NULL,
  `cancellation_scope_recovery_until` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `workflow_runs_workflow_instance_id_run_number_unique` (`workflow_instance_id`,`run_number`),
  KEY `workflow_runs_workflow_instance_id_index` (`workflow_instance_id`),
  KEY `workflow_runs_namespace_index` (`namespace`),
  KEY `workflow_runs_business_key_index` (`business_key`),
  KEY `workflow_runs_sticky_worker_id_index` (`sticky_worker_id`),
  KEY `workflow_runs_sticky_until_index` (`sticky_until`),
  KEY `workflow_runs_archived_at_index` (`archived_at`),
  KEY `workflow_runs_archive_command_id_index` (`archive_command_id`),
  KEY `workflow_runs_import_source_index` (`import_source`),
  KEY `workflow_runs_import_id_index` (`import_id`),
  KEY `workflow_runs_import_dedupe_key_index` (`import_dedupe_key`),
  KEY `workflow_runs_imported_at_index` (`imported_at`),
  KEY `workflow_runs_prom_metrics_queue_idx` (`namespace`,`queue`),
  KEY `workflow_runs_namespace_status_quota_idx` (`namespace`,`status`),
  KEY `workflow_runs_cancellation_request_command_id_index` (`cancellation_request_command_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_run_lineage_entries` (
  `id` varchar(64) NOT NULL,
  `workflow_run_id` varchar(26) NOT NULL,
  `workflow_instance_id` varchar(191) NOT NULL,
  `direction` varchar(255) NOT NULL,
  `lineage_id` varchar(191) NOT NULL,
  `position` int(10) unsigned NOT NULL,
  `link_type` varchar(255) NOT NULL,
  `child_call_id` varchar(26) DEFAULT NULL,
  `sequence` int(10) unsigned DEFAULT NULL,
  `is_primary_parent` tinyint(1) NOT NULL DEFAULT 0,
  `related_workflow_instance_id` varchar(191) DEFAULT NULL,
  `related_workflow_run_id` varchar(26) DEFAULT NULL,
  `related_run_number` int(10) unsigned DEFAULT NULL,
  `related_workflow_type` varchar(191) DEFAULT NULL,
  `related_workflow_class` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `status_bucket` varchar(255) DEFAULT NULL,
  `closed_reason` varchar(255) DEFAULT NULL,
  `linked_at` timestamp(6) NULL DEFAULT NULL,
  `payload` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`payload`)),
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `workflow_run_lineage_run_direction_lineage_unique` (`workflow_run_id`,`direction`,`lineage_id`),
  KEY `workflow_run_lineage_run_direction_position_index` (`workflow_run_id`,`direction`,`position`),
  KEY `workflow_run_lineage_instance_direction_type_index` (`workflow_instance_id`,`direction`,`link_type`),
  KEY `workflow_run_lineage_entries_workflow_run_id_index` (`workflow_run_id`),
  KEY `workflow_run_lineage_entries_workflow_instance_id_index` (`workflow_instance_id`),
  KEY `workflow_run_lineage_entries_direction_index` (`direction`),
  KEY `workflow_run_lineage_entries_link_type_index` (`link_type`),
  KEY `workflow_run_lineage_entries_child_call_id_index` (`child_call_id`),
  KEY `workflow_run_lineage_entries_sequence_index` (`sequence`),
  KEY `workflow_run_lineage_entries_is_primary_parent_index` (`is_primary_parent`),
  KEY `workflow_run_lineage_entries_related_workflow_instance_id_index` (`related_workflow_instance_id`),
  KEY `workflow_run_lineage_entries_related_workflow_run_id_index` (`related_workflow_run_id`),
  KEY `workflow_run_lineage_entries_related_workflow_type_index` (`related_workflow_type`),
  KEY `workflow_run_lineage_entries_status_index` (`status`),
  KEY `workflow_run_lineage_entries_status_bucket_index` (`status_bucket`),
  KEY `workflow_run_lineage_entries_closed_reason_index` (`closed_reason`),
  KEY `workflow_run_lineage_entries_linked_at_index` (`linked_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_run_summaries` (
  `id` varchar(26) NOT NULL,
  `workflow_instance_id` varchar(191) NOT NULL,
  `run_number` int(10) unsigned NOT NULL,
  `is_current_run` tinyint(1) NOT NULL DEFAULT 0,
  `engine_source` varchar(255) NOT NULL DEFAULT 'v2',
  `projection_schema_version` smallint(5) unsigned DEFAULT NULL,
  `class` varchar(255) NOT NULL,
  `workflow_type` varchar(255) NOT NULL,
  `namespace` varchar(255) DEFAULT NULL,
  `compatibility` varchar(255) DEFAULT NULL,
  `declared_entry_mode` varchar(255) DEFAULT NULL,
  `declared_contract_source` varchar(255) DEFAULT NULL,
  `business_key` varchar(191) DEFAULT NULL,
  `visibility_labels` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`visibility_labels`)),
  `status` varchar(255) NOT NULL,
  `status_bucket` varchar(255) NOT NULL,
  `closed_reason` varchar(255) DEFAULT NULL,
  `connection` varchar(255) DEFAULT NULL,
  `queue` varchar(255) DEFAULT NULL,
  `started_at` timestamp(6) NULL DEFAULT NULL,
  `sort_timestamp` timestamp(6) NULL DEFAULT NULL,
  `sort_key` varchar(64) DEFAULT NULL,
  `closed_at` timestamp(6) NULL DEFAULT NULL,
  `archived_at` timestamp(6) NULL DEFAULT NULL,
  `archive_command_id` varchar(26) DEFAULT NULL,
  `archive_reason` varchar(255) DEFAULT NULL,
  `duration_ms` bigint(20) DEFAULT NULL,
  `wait_kind` varchar(255) DEFAULT NULL,
  `wait_reason` text DEFAULT NULL,
  `wait_started_at` timestamp(6) NULL DEFAULT NULL,
  `wait_deadline_at` timestamp(6) NULL DEFAULT NULL,
  `open_wait_id` varchar(191) DEFAULT NULL,
  `resume_source_kind` varchar(255) DEFAULT NULL,
  `resume_source_id` varchar(191) DEFAULT NULL,
  `next_task_at` timestamp(6) NULL DEFAULT NULL,
  `liveness_state` varchar(255) DEFAULT NULL,
  `liveness_reason` text DEFAULT NULL,
  `repair_blocked_reason` varchar(255) DEFAULT NULL,
  `repair_attention` tinyint(1) NOT NULL DEFAULT 0,
  `task_problem` tinyint(1) NOT NULL DEFAULT 0,
  `next_task_id` varchar(26) DEFAULT NULL,
  `next_task_type` varchar(255) DEFAULT NULL,
  `next_task_status` varchar(255) DEFAULT NULL,
  `next_task_lease_expires_at` timestamp(6) NULL DEFAULT NULL,
  `exception_count` int(10) unsigned NOT NULL DEFAULT 0,
  `history_event_count` int(10) unsigned NOT NULL DEFAULT 0,
  `history_size_bytes` bigint(20) unsigned NOT NULL DEFAULT 0,
  `history_fan_out` int(10) unsigned NOT NULL DEFAULT 0,
  `continue_as_new_recommended` tinyint(1) NOT NULL DEFAULT 0,
  `history_budget_pressure` varchar(32) NOT NULL DEFAULT 'ok',
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `workflow_run_summaries_status_bucket_started_at_index` (`status_bucket`,`started_at`),
  KEY `workflow_run_summaries_sort_order_index` (`sort_timestamp`,`id`),
  KEY `wfrs_namespace_sort_idx` (`namespace`,`sort_timestamp`,`id`),
  KEY `wfrs_namespace_type_sort_idx` (`namespace`,`workflow_type`,`sort_timestamp`,`id`),
  KEY `wfrs_namespace_status_sort_idx` (`namespace`,`status_bucket`,`sort_timestamp`,`id`),
  KEY `workflow_run_summaries_sort_key_index` (`sort_key`),
  KEY `workflow_run_summaries_workflow_instance_id_index` (`workflow_instance_id`),
  KEY `workflow_run_summaries_is_current_run_index` (`is_current_run`),
  KEY `workflow_run_summaries_projection_schema_version_index` (`projection_schema_version`),
  KEY `workflow_run_summaries_namespace_index` (`namespace`),
  KEY `wfrs_decl_entry_mode_idx` (`declared_entry_mode`),
  KEY `wfrs_decl_contract_source_idx` (`declared_contract_source`),
  KEY `workflow_run_summaries_business_key_index` (`business_key`),
  KEY `workflow_run_summaries_status_index` (`status`),
  KEY `workflow_run_summaries_status_bucket_index` (`status_bucket`),
  KEY `workflow_run_summaries_archived_at_index` (`archived_at`),
  KEY `workflow_run_summaries_archive_command_id_index` (`archive_command_id`),
  KEY `workflow_run_summaries_repair_blocked_reason_index` (`repair_blocked_reason`),
  KEY `workflow_run_summaries_repair_attention_index` (`repair_attention`),
  KEY `workflow_run_summaries_continue_as_new_recommended_index` (`continue_as_new_recommended`),
  KEY `workflow_run_summaries_history_budget_pressure_index` (`history_budget_pressure`),
  KEY `wfrs_prom_metrics_series_idx` (`namespace`,`queue`,`workflow_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_run_timeline_entries` (
  `id` varchar(64) NOT NULL,
  `workflow_run_id` varchar(26) NOT NULL,
  `workflow_instance_id` varchar(191) NOT NULL,
  `history_event_id` varchar(26) NOT NULL,
  `sequence` int(10) unsigned NOT NULL,
  `type` varchar(255) NOT NULL,
  `kind` varchar(255) NOT NULL,
  `entry_kind` varchar(255) NOT NULL DEFAULT 'point',
  `source_kind` varchar(255) DEFAULT NULL,
  `source_id` varchar(191) DEFAULT NULL,
  `summary` text DEFAULT NULL,
  `recorded_at` timestamp(6) NULL DEFAULT NULL,
  `command_id` varchar(26) DEFAULT NULL,
  `command_sequence` int(10) unsigned DEFAULT NULL,
  `task_id` varchar(26) DEFAULT NULL,
  `activity_execution_id` varchar(26) DEFAULT NULL,
  `timer_id` varchar(191) DEFAULT NULL,
  `failure_id` varchar(26) DEFAULT NULL,
  `payload` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`payload`)),
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `workflow_run_timeline_run_event_unique` (`workflow_run_id`,`history_event_id`),
  KEY `workflow_run_timeline_run_sequence_index` (`workflow_run_id`,`sequence`),
  KEY `workflow_run_timeline_instance_kind_recorded_index` (`workflow_instance_id`,`kind`,`recorded_at`),
  KEY `workflow_run_timeline_entries_workflow_run_id_index` (`workflow_run_id`),
  KEY `workflow_run_timeline_entries_workflow_instance_id_index` (`workflow_instance_id`),
  KEY `workflow_run_timeline_entries_history_event_id_index` (`history_event_id`),
  KEY `workflow_run_timeline_entries_sequence_index` (`sequence`),
  KEY `workflow_run_timeline_entries_type_index` (`type`),
  KEY `workflow_run_timeline_entries_kind_index` (`kind`),
  KEY `workflow_run_timeline_entries_source_kind_index` (`source_kind`),
  KEY `workflow_run_timeline_entries_source_id_index` (`source_id`),
  KEY `workflow_run_timeline_entries_recorded_at_index` (`recorded_at`),
  KEY `workflow_run_timeline_entries_command_id_index` (`command_id`),
  KEY `workflow_run_timeline_entries_command_sequence_index` (`command_sequence`),
  KEY `workflow_run_timeline_entries_task_id_index` (`task_id`),
  KEY `workflow_run_timeline_entries_activity_execution_id_index` (`activity_execution_id`),
  KEY `workflow_run_timeline_entries_timer_id_index` (`timer_id`),
  KEY `workflow_run_timeline_entries_failure_id_index` (`failure_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_run_timers` (
  `id` varchar(26) NOT NULL,
  `workflow_run_id` varchar(26) NOT NULL,
  `sequence` int(10) unsigned NOT NULL,
  `status` varchar(255) NOT NULL,
  `delay_seconds` bigint(20) unsigned NOT NULL,
  `fire_at` timestamp(6) NOT NULL,
  `fired_at` timestamp(6) NULL DEFAULT NULL,
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `workflow_run_timers_workflow_run_id_sequence_unique` (`workflow_run_id`,`sequence`),
  KEY `workflow_run_timers_status_fire_at_index` (`status`,`fire_at`),
  KEY `workflow_run_timers_workflow_run_id_index` (`workflow_run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_run_timer_entries` (
  `id` varchar(64) NOT NULL,
  `workflow_run_id` varchar(26) NOT NULL,
  `workflow_instance_id` varchar(191) NOT NULL,
  `timer_id` varchar(191) NOT NULL,
  `schema_version` smallint(5) unsigned NOT NULL DEFAULT 1,
  `position` int(10) unsigned NOT NULL,
  `sequence` int(10) unsigned DEFAULT NULL,
  `status` varchar(255) NOT NULL,
  `source_status` varchar(255) DEFAULT NULL,
  `delay_seconds` int(11) DEFAULT NULL,
  `fire_at` timestamp(6) NULL DEFAULT NULL,
  `fired_at` timestamp(6) NULL DEFAULT NULL,
  `cancelled_at` timestamp(6) NULL DEFAULT NULL,
  `timer_kind` varchar(191) DEFAULT NULL,
  `condition_wait_id` varchar(191) DEFAULT NULL,
  `condition_key` varchar(191) DEFAULT NULL,
  `condition_definition_fingerprint` varchar(191) DEFAULT NULL,
  `history_authority` varchar(255) DEFAULT NULL,
  `history_unsupported_reason` varchar(255) DEFAULT NULL,
  `payload` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`payload`)),
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `workflow_run_timer_entries_run_timer_unique` (`workflow_run_id`,`timer_id`),
  KEY `workflow_run_timer_entries_run_status_position_index` (`workflow_run_id`,`status`,`position`),
  KEY `workflow_run_timer_entries_instance_kind_status_index` (`workflow_instance_id`,`timer_kind`,`status`),
  KEY `workflow_run_timer_entries_workflow_run_id_index` (`workflow_run_id`),
  KEY `workflow_run_timer_entries_workflow_instance_id_index` (`workflow_instance_id`),
  KEY `workflow_run_timer_entries_sequence_index` (`sequence`),
  KEY `workflow_run_timer_entries_status_index` (`status`),
  KEY `workflow_run_timer_entries_source_status_index` (`source_status`),
  KEY `workflow_run_timer_entries_timer_kind_index` (`timer_kind`),
  KEY `workflow_run_timer_entries_condition_wait_id_index` (`condition_wait_id`),
  KEY `workflow_run_timer_entries_condition_key_index` (`condition_key`),
  KEY `workflow_run_timer_entries_history_authority_index` (`history_authority`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_run_waits` (
  `id` varchar(64) NOT NULL,
  `workflow_run_id` varchar(26) NOT NULL,
  `workflow_instance_id` varchar(191) NOT NULL,
  `wait_id` varchar(191) NOT NULL,
  `position` int(10) unsigned NOT NULL,
  `kind` varchar(255) NOT NULL,
  `sequence` int(10) unsigned DEFAULT NULL,
  `status` varchar(255) NOT NULL,
  `source_status` varchar(255) DEFAULT NULL,
  `summary` text DEFAULT NULL,
  `opened_at` timestamp(6) NULL DEFAULT NULL,
  `deadline_at` timestamp(6) NULL DEFAULT NULL,
  `resolved_at` timestamp(6) NULL DEFAULT NULL,
  `target_name` varchar(191) DEFAULT NULL,
  `target_type` varchar(191) DEFAULT NULL,
  `task_backed` tinyint(1) NOT NULL DEFAULT 0,
  `external_only` tinyint(1) NOT NULL DEFAULT 0,
  `resume_source_kind` varchar(191) DEFAULT NULL,
  `resume_source_id` varchar(191) DEFAULT NULL,
  `task_id` varchar(26) DEFAULT NULL,
  `task_type` varchar(255) DEFAULT NULL,
  `task_status` varchar(255) DEFAULT NULL,
  `command_id` varchar(26) DEFAULT NULL,
  `command_sequence` int(10) unsigned DEFAULT NULL,
  `command_status` varchar(255) DEFAULT NULL,
  `command_outcome` varchar(255) DEFAULT NULL,
  `history_authority` varchar(255) DEFAULT NULL,
  `history_unsupported_reason` varchar(255) DEFAULT NULL,
  `payload` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`payload`)),
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `workflow_run_waits_run_wait_unique` (`workflow_run_id`,`wait_id`),
  KEY `workflow_run_waits_run_status_position_index` (`workflow_run_id`,`status`,`position`),
  KEY `workflow_run_waits_instance_kind_status_index` (`workflow_instance_id`,`kind`,`status`),
  KEY `workflow_run_waits_workflow_run_id_index` (`workflow_run_id`),
  KEY `workflow_run_waits_workflow_instance_id_index` (`workflow_instance_id`),
  KEY `workflow_run_waits_kind_index` (`kind`),
  KEY `workflow_run_waits_sequence_index` (`sequence`),
  KEY `workflow_run_waits_status_index` (`status`),
  KEY `workflow_run_waits_source_status_index` (`source_status`),
  KEY `workflow_run_waits_target_name_index` (`target_name`),
  KEY `workflow_run_waits_task_backed_index` (`task_backed`),
  KEY `workflow_run_waits_resume_source_kind_index` (`resume_source_kind`),
  KEY `workflow_run_waits_resume_source_id_index` (`resume_source_id`),
  KEY `workflow_run_waits_task_id_index` (`task_id`),
  KEY `workflow_run_waits_command_id_index` (`command_id`),
  KEY `workflow_run_waits_history_authority_index` (`history_authority`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_schedules` (
  `id` varchar(26) NOT NULL,
  `schedule_id` varchar(255) NOT NULL,
  `namespace` varchar(255) DEFAULT NULL,
  `spec` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`spec`)),
  `action` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`action`)),
  `status` varchar(16) NOT NULL DEFAULT 'active',
  `overlap_policy` varchar(32) NOT NULL DEFAULT 'skip',
  `note` text DEFAULT NULL,
  `memo` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`memo`)),
  `search_attributes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`search_attributes`)),
  `visibility_labels` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`visibility_labels`)),
  `jitter_seconds` int(10) unsigned NOT NULL DEFAULT 0,
  `max_runs` bigint(20) unsigned DEFAULT NULL,
  `remaining_actions` bigint(20) unsigned DEFAULT NULL,
  `fires_count` bigint(20) unsigned NOT NULL DEFAULT 0,
  `failures_count` bigint(20) unsigned NOT NULL DEFAULT 0,
  `recent_actions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`recent_actions`)),
  `buffered_actions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`buffered_actions`)),
  `last_fired_at` timestamp(6) NULL DEFAULT NULL,
  `next_fire_at` timestamp(6) NULL DEFAULT NULL,
  `latest_workflow_instance_id` varchar(191) DEFAULT NULL,
  `connection` varchar(255) DEFAULT NULL,
  `queue` varchar(255) DEFAULT NULL,
  `paused_at` timestamp(6) NULL DEFAULT NULL,
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `last_skip_reason` varchar(64) DEFAULT NULL,
  `last_skipped_at` timestamp(6) NULL DEFAULT NULL,
  `skipped_trigger_count` bigint(20) unsigned NOT NULL DEFAULT 0,
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `workflow_schedules_namespace_schedule_id_unique` (`namespace`,`schedule_id`),
  KEY `workflow_schedules_status_next_fire_at_index` (`status`,`next_fire_at`),
  KEY `workflow_schedules_namespace_index` (`namespace`),
  KEY `workflow_schedules_latest_workflow_instance_id_index` (`latest_workflow_instance_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_schedule_history_events` (
  `id` varchar(26) NOT NULL,
  `workflow_schedule_id` varchar(26) NOT NULL,
  `schedule_id` varchar(255) NOT NULL,
  `namespace` varchar(255) DEFAULT NULL,
  `sequence` int(10) unsigned NOT NULL,
  `event_type` varchar(255) NOT NULL,
  `payload` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`payload`)),
  `workflow_instance_id` varchar(191) DEFAULT NULL,
  `workflow_run_id` varchar(26) DEFAULT NULL,
  `recorded_at` timestamp(6) NULL DEFAULT NULL,
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  `occurrence_at_utc` varchar(26) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `wf_schedule_history_schedule_sequence_unique` (`workflow_schedule_id`,`sequence`),
  KEY `wf_schedule_history_namespace_schedule_idx` (`namespace`,`schedule_id`),
  KEY `wf_schedule_history_event_recorded_idx` (`event_type`,`recorded_at`),
  KEY `wf_schedule_history_workflow_schedule_idx` (`workflow_schedule_id`),
  KEY `wf_schedule_history_schedule_idx` (`schedule_id`),
  KEY `wf_schedule_history_namespace_idx` (`namespace`),
  KEY `wf_schedule_history_instance_idx` (`workflow_instance_id`),
  KEY `wf_schedule_history_run_idx` (`workflow_run_id`),
  KEY `wf_schedule_history_occurrence_idx` (`workflow_schedule_id`,`event_type`,`occurrence_at_utc`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_search_attributes` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `workflow_run_id` varchar(26) NOT NULL,
  `workflow_instance_id` varchar(191) NOT NULL,
  `key` varchar(191) NOT NULL COMMENT 'Attribute name (e.g., "customer_id", "priority", "region")',
  `type` varchar(16) NOT NULL COMMENT 'Type: string, keyword, int, float, bool, datetime',
  `value_string` text DEFAULT NULL COMMENT 'For type=string (max 2048 chars enforced at app level)',
  `value_keyword` varchar(255) DEFAULT NULL COMMENT 'For type=keyword (exact match, indexed)',
  `value_keyword_list` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'For type=keyword_list (ordered exact-match values)' CHECK (json_valid(`value_keyword_list`)),
  `value_int` bigint(20) DEFAULT NULL COMMENT 'For type=int',
  `value_float` double DEFAULT NULL COMMENT 'For type=float',
  `value_bool` tinyint(1) DEFAULT NULL COMMENT 'For type=bool',
  `value_datetime` timestamp(6) NULL DEFAULT NULL COMMENT 'For type=datetime (microsecond precision)',
  `upserted_at_sequence` int(10) unsigned NOT NULL COMMENT 'History sequence when this attribute was last upserted',
  `inherited_from_parent` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'True if inherited via continue-as-new',
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `workflow_search_attrs_run_key_unique` (`workflow_run_id`,`key`),
  KEY `workflow_search_attrs_instance_key_type` (`workflow_instance_id`,`key`,`type`),
  KEY `workflow_search_attrs_key_keyword` (`key`,`value_keyword`),
  KEY `workflow_search_attrs_key_int` (`key`,`value_int`),
  KEY `workflow_search_attrs_key_float` (`key`,`value_float`),
  KEY `workflow_search_attrs_key_bool` (`key`,`value_bool`),
  KEY `workflow_search_attrs_key_datetime` (`key`,`value_datetime`),
  KEY `workflow_search_attributes_workflow_run_id_index` (`workflow_run_id`),
  KEY `workflow_search_attributes_workflow_instance_id_index` (`workflow_instance_id`),
  KEY `workflow_search_attributes_value_keyword_index` (`value_keyword`),
  KEY `workflow_search_attributes_value_int_index` (`value_int`),
  KEY `workflow_search_attributes_value_float_index` (`value_float`),
  KEY `workflow_search_attributes_value_bool_index` (`value_bool`),
  KEY `workflow_search_attributes_value_datetime_index` (`value_datetime`),
  CONSTRAINT `workflow_search_attributes_workflow_run_id_foreign` FOREIGN KEY (`workflow_run_id`) REFERENCES `workflow_runs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_services` (
  `id` varchar(26) NOT NULL,
  `workflow_service_endpoint_id` varchar(26) NOT NULL,
  `namespace` varchar(255) DEFAULT NULL,
  `service_name` varchar(191) NOT NULL,
  `description` text DEFAULT NULL,
  `boundary_policy` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`boundary_policy`)),
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `wf_services_namespace_endpoint_name_unique` (`namespace`,`workflow_service_endpoint_id`,`service_name`),
  KEY `wf_services_namespace_name_idx` (`namespace`,`service_name`),
  KEY `wf_services_endpoint_idx` (`workflow_service_endpoint_id`),
  KEY `wf_services_namespace_idx` (`namespace`),
  KEY `wf_services_name_idx` (`service_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_service_calls` (
  `id` varchar(26) NOT NULL,
  `workflow_service_endpoint_id` varchar(26) DEFAULT NULL,
  `workflow_service_id` varchar(26) DEFAULT NULL,
  `workflow_service_operation_id` varchar(26) DEFAULT NULL,
  `namespace` varchar(255) DEFAULT NULL,
  `endpoint_name` varchar(191) NOT NULL,
  `service_name` varchar(191) NOT NULL,
  `operation_name` varchar(191) NOT NULL,
  `caller_namespace` varchar(255) DEFAULT NULL,
  `caller_workflow_instance_id` varchar(191) DEFAULT NULL,
  `caller_workflow_run_id` varchar(26) DEFAULT NULL,
  `target_namespace` varchar(255) DEFAULT NULL,
  `linked_workflow_instance_id` varchar(191) DEFAULT NULL,
  `linked_workflow_run_id` varchar(26) DEFAULT NULL,
  `linked_workflow_update_id` varchar(26) DEFAULT NULL,
  `status` varchar(32) NOT NULL,
  `outcome` varchar(64) DEFAULT NULL,
  `operation_mode` varchar(32) NOT NULL,
  `resolved_binding_kind` varchar(64) DEFAULT NULL,
  `resolved_target_reference` varchar(191) DEFAULT NULL,
  `payload_codec` varchar(255) DEFAULT NULL,
  `input_payload_reference` varchar(191) DEFAULT NULL,
  `output_payload_reference` varchar(191) DEFAULT NULL,
  `failure_payload_reference` varchar(191) DEFAULT NULL,
  `failure_message` text DEFAULT NULL,
  `idempotency_key` varchar(191) DEFAULT NULL,
  `deadline_policy` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`deadline_policy`)),
  `idempotency_policy` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`idempotency_policy`)),
  `cancellation_policy` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`cancellation_policy`)),
  `retry_policy` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`retry_policy`)),
  `boundary_policy` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`boundary_policy`)),
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  `outcome_category` varchar(32) DEFAULT NULL,
  `outcome_reason` varchar(191) DEFAULT NULL,
  `outcome_message` text DEFAULT NULL,
  `outcome_metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`outcome_metadata`)),
  `policy_name` varchar(191) DEFAULT NULL,
  `retry_after_seconds` int(10) unsigned DEFAULT NULL,
  `caller_principal_subject` varchar(191) DEFAULT NULL,
  `caller_principal_method` varchar(64) DEFAULT NULL,
  `caller_principal_roles` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`caller_principal_roles`)),
  `caller_principal_tenant` varchar(191) DEFAULT NULL,
  `caller_principal_claims` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`caller_principal_claims`)),
  `accepted_at` timestamp(6) NULL DEFAULT NULL,
  `started_at` timestamp(6) NULL DEFAULT NULL,
  `completed_at` timestamp(6) NULL DEFAULT NULL,
  `failed_at` timestamp(6) NULL DEFAULT NULL,
  `cancelled_at` timestamp(6) NULL DEFAULT NULL,
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `wf_service_calls_namespace_status_idx` (`namespace`,`status`),
  KEY `wf_service_calls_caller_status_idx` (`caller_namespace`,`status`),
  KEY `wf_service_calls_target_status_idx` (`target_namespace`,`status`),
  KEY `wf_service_calls_namespace_outcome_idx` (`namespace`,`outcome`),
  KEY `wf_service_calls_caller_outcome_idx` (`caller_namespace`,`outcome`),
  KEY `wf_service_calls_target_outcome_idx` (`target_namespace`,`outcome`),
  KEY `wf_service_calls_endpoint_idx` (`workflow_service_endpoint_id`),
  KEY `wf_service_calls_service_idx` (`workflow_service_id`),
  KEY `wf_service_calls_operation_idx` (`workflow_service_operation_id`),
  KEY `wf_service_calls_namespace_idx` (`namespace`),
  KEY `wf_service_calls_caller_namespace_idx` (`caller_namespace`),
  KEY `wf_service_calls_caller_instance_idx` (`caller_workflow_instance_id`),
  KEY `wf_service_calls_caller_run_idx` (`caller_workflow_run_id`),
  KEY `wf_service_calls_target_namespace_idx` (`target_namespace`),
  KEY `wf_service_calls_linked_instance_idx` (`linked_workflow_instance_id`),
  KEY `wf_service_calls_linked_run_idx` (`linked_workflow_run_id`),
  KEY `wf_service_calls_linked_update_idx` (`linked_workflow_update_id`),
  KEY `wf_service_calls_status_idx` (`status`),
  KEY `wf_service_calls_outcome_idx` (`outcome`),
  KEY `wf_service_calls_mode_idx` (`operation_mode`),
  KEY `wf_service_calls_binding_kind_idx` (`resolved_binding_kind`),
  KEY `wf_service_calls_idempotency_idx` (`idempotency_key`),
  KEY `wf_service_calls_outcome_category_idx` (`outcome_category`),
  KEY `wf_service_calls_policy_idx` (`policy_name`),
  KEY `wf_service_calls_principal_subject_idx` (`caller_principal_subject`),
  KEY `wf_service_calls_accepted_at_idx` (`accepted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_service_endpoints` (
  `id` varchar(26) NOT NULL,
  `namespace` varchar(255) DEFAULT NULL,
  `endpoint_name` varchar(191) NOT NULL,
  `description` text DEFAULT NULL,
  `boundary_policy` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`boundary_policy`)),
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `wf_service_endpoints_namespace_name_unique` (`namespace`,`endpoint_name`),
  KEY `wf_service_endpoints_namespace_idx` (`namespace`),
  KEY `wf_service_endpoints_name_idx` (`endpoint_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_service_operations` (
  `id` varchar(26) NOT NULL,
  `workflow_service_endpoint_id` varchar(26) NOT NULL,
  `workflow_service_id` varchar(26) NOT NULL,
  `namespace` varchar(255) DEFAULT NULL,
  `operation_name` varchar(191) NOT NULL,
  `description` text DEFAULT NULL,
  `operation_mode` varchar(32) NOT NULL,
  `handler_binding_kind` varchar(64) NOT NULL,
  `handler_target_reference` varchar(191) DEFAULT NULL,
  `handler_binding` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`handler_binding`)),
  `deadline_policy` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`deadline_policy`)),
  `idempotency_policy` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`idempotency_policy`)),
  `cancellation_policy` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`cancellation_policy`)),
  `retry_policy` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`retry_policy`)),
  `boundary_policy` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`boundary_policy`)),
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `wf_service_ops_namespace_service_name_unique` (`namespace`,`workflow_service_id`,`operation_name`),
  KEY `wf_service_ops_namespace_name_idx` (`namespace`,`operation_name`),
  KEY `wf_service_ops_endpoint_idx` (`workflow_service_endpoint_id`),
  KEY `wf_service_ops_service_idx` (`workflow_service_id`),
  KEY `wf_service_ops_namespace_idx` (`namespace`),
  KEY `wf_service_ops_name_idx` (`operation_name`),
  KEY `wf_service_ops_mode_idx` (`operation_mode`),
  KEY `wf_service_ops_binding_kind_idx` (`handler_binding_kind`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_signal_records` (
  `id` varchar(26) NOT NULL,
  `workflow_command_id` varchar(26) NOT NULL,
  `workflow_instance_id` varchar(191) DEFAULT NULL,
  `workflow_run_id` varchar(26) DEFAULT NULL,
  `target_scope` varchar(255) NOT NULL DEFAULT 'instance',
  `requested_workflow_run_id` varchar(26) DEFAULT NULL,
  `resolved_workflow_run_id` varchar(26) DEFAULT NULL,
  `signal_name` varchar(255) NOT NULL,
  `signal_wait_id` varchar(255) DEFAULT NULL,
  `status` varchar(255) NOT NULL,
  `outcome` varchar(255) DEFAULT NULL,
  `command_sequence` int(10) unsigned DEFAULT NULL,
  `workflow_sequence` int(10) unsigned DEFAULT NULL,
  `payload_codec` varchar(255) DEFAULT NULL,
  `arguments` longtext DEFAULT NULL,
  `validation_errors` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`validation_errors`)),
  `rejection_reason` varchar(255) DEFAULT NULL,
  `received_at` timestamp(6) NULL DEFAULT NULL,
  `applied_at` timestamp(6) NULL DEFAULT NULL,
  `rejected_at` timestamp(6) NULL DEFAULT NULL,
  `closed_at` timestamp(6) NULL DEFAULT NULL,
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `workflow_signal_records_workflow_command_id_unique` (`workflow_command_id`),
  KEY `workflow_signal_records_workflow_instance_id_index` (`workflow_instance_id`),
  KEY `workflow_signal_records_workflow_run_id_index` (`workflow_run_id`),
  KEY `workflow_signal_records_requested_workflow_run_id_index` (`requested_workflow_run_id`),
  KEY `workflow_signal_records_resolved_workflow_run_id_index` (`resolved_workflow_run_id`),
  KEY `workflow_signal_records_signal_name_index` (`signal_name`),
  KEY `workflow_signal_records_signal_wait_id_index` (`signal_wait_id`),
  KEY `workflow_signal_records_status_index` (`status`),
  KEY `workflow_signal_records_outcome_index` (`outcome`),
  KEY `workflow_signal_records_command_sequence_index` (`command_sequence`),
  KEY `workflow_signal_records_workflow_sequence_index` (`workflow_sequence`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_tasks` (
  `id` varchar(26) NOT NULL,
  `workflow_run_id` varchar(26) NOT NULL,
  `namespace` varchar(255) DEFAULT NULL,
  `task_type` varchar(255) NOT NULL,
  `status` varchar(255) NOT NULL,
  `compatibility` varchar(255) DEFAULT NULL,
  `payload` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`payload`)),
  `connection` varchar(255) DEFAULT NULL,
  `queue` varchar(255) DEFAULT NULL,
  `priority` tinyint(3) unsigned NOT NULL DEFAULT 5,
  `fairness_key` varchar(64) DEFAULT NULL,
  `fairness_weight` smallint(5) unsigned NOT NULL DEFAULT 1,
  `sticky_worker_id` varchar(255) DEFAULT NULL,
  `sticky_until` timestamp(6) NULL DEFAULT NULL,
  `sticky_replay_mode` varchar(255) DEFAULT NULL,
  `sticky_claimed_at` timestamp(6) NULL DEFAULT NULL,
  `available_at` timestamp(6) NULL DEFAULT NULL,
  `leased_at` timestamp(6) NULL DEFAULT NULL,
  `lease_owner` varchar(255) DEFAULT NULL,
  `lease_expires_at` timestamp(6) NULL DEFAULT NULL,
  `attempt_count` int(10) unsigned NOT NULL DEFAULT 0,
  `last_dispatch_attempt_at` timestamp(6) NULL DEFAULT NULL,
  `last_dispatched_at` timestamp(6) NULL DEFAULT NULL,
  `last_dispatch_error` text DEFAULT NULL,
  `last_claim_failed_at` timestamp(6) NULL DEFAULT NULL,
  `last_claim_error` text DEFAULT NULL,
  `repair_count` int(10) unsigned NOT NULL DEFAULT 0,
  `repair_available_at` timestamp(6) NULL DEFAULT NULL,
  `last_error` text DEFAULT NULL,
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `workflow_tasks_status_available_at_index` (`status`,`available_at`),
  KEY `workflow_tasks_workflow_run_id_index` (`workflow_run_id`),
  KEY `workflow_tasks_namespace_index` (`namespace`),
  KEY `workflow_tasks_sticky_worker_id_index` (`sticky_worker_id`),
  KEY `workflow_tasks_sticky_until_index` (`sticky_until`),
  KEY `workflow_tasks_sticky_replay_mode_index` (`sticky_replay_mode`),
  KEY `workflow_tasks_sticky_claimed_at_index` (`sticky_claimed_at`),
  KEY `workflow_tasks_dispatch_order_index` (`queue`,`status`,`priority`,`available_at`),
  KEY `workflow_tasks_namespace_queue_status_idx` (`namespace`,`queue`,`status`),
  KEY `workflow_tasks_fairness_class_index` (`queue`,`status`,`fairness_key`),
  KEY `workflow_tasks_prom_metrics_queue_idx` (`namespace`,`queue`),
  KEY `dw_workflow_tasks_poll` (`namespace`(64),`queue`(64),`task_type`(16),`status`(16),`available_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_task_poll_cursors` (
  `namespace` varchar(128) NOT NULL,
  `task_queue` varchar(255) NOT NULL,
  `next_task_kind` varchar(32) NOT NULL,
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`namespace`,`task_queue`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_updates` (
  `id` varchar(26) NOT NULL,
  `workflow_command_id` varchar(26) NOT NULL,
  `workflow_instance_id` varchar(191) DEFAULT NULL,
  `workflow_run_id` varchar(26) DEFAULT NULL,
  `target_scope` varchar(255) NOT NULL DEFAULT 'instance',
  `requested_workflow_run_id` varchar(26) DEFAULT NULL,
  `resolved_workflow_run_id` varchar(26) DEFAULT NULL,
  `update_name` varchar(255) NOT NULL,
  `status` varchar(255) NOT NULL,
  `outcome` varchar(255) DEFAULT NULL,
  `command_sequence` int(10) unsigned DEFAULT NULL,
  `workflow_sequence` int(10) unsigned DEFAULT NULL,
  `payload_codec` varchar(255) DEFAULT NULL,
  `arguments` longtext DEFAULT NULL,
  `result` longtext DEFAULT NULL,
  `validation_errors` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`validation_errors`)),
  `rejection_reason` varchar(255) DEFAULT NULL,
  `failure_id` varchar(26) DEFAULT NULL,
  `failure_message` text DEFAULT NULL,
  `accepted_at` timestamp(6) NULL DEFAULT NULL,
  `applied_at` timestamp(6) NULL DEFAULT NULL,
  `rejected_at` timestamp(6) NULL DEFAULT NULL,
  `closed_at` timestamp(6) NULL DEFAULT NULL,
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `workflow_updates_workflow_command_id_unique` (`workflow_command_id`),
  KEY `workflow_updates_workflow_instance_id_index` (`workflow_instance_id`),
  KEY `workflow_updates_workflow_run_id_index` (`workflow_run_id`),
  KEY `workflow_updates_requested_workflow_run_id_index` (`requested_workflow_run_id`),
  KEY `workflow_updates_resolved_workflow_run_id_index` (`resolved_workflow_run_id`),
  KEY `workflow_updates_update_name_index` (`update_name`),
  KEY `workflow_updates_status_index` (`status`),
  KEY `workflow_updates_outcome_index` (`outcome`),
  KEY `workflow_updates_command_sequence_index` (`command_sequence`),
  KEY `workflow_updates_workflow_sequence_index` (`workflow_sequence`),
  KEY `workflow_updates_failure_id_index` (`failure_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_update_validation_tasks` (
  `id` varchar(26) NOT NULL,
  `idempotency_key` varchar(64) NOT NULL,
  `namespace` varchar(255) NOT NULL,
  `workflow_instance_id` varchar(191) NOT NULL,
  `workflow_run_id` varchar(26) NOT NULL,
  `workflow_type` varchar(255) NOT NULL,
  `task_queue` varchar(255) NOT NULL,
  `compatibility` varchar(255) DEFAULT NULL,
  `workflow_definition_fingerprint` varchar(255) DEFAULT NULL,
  `update_name` varchar(255) NOT NULL,
  `request_id` varchar(255) NOT NULL,
  `input_hash` varchar(64) NOT NULL,
  `payload_codec` varchar(255) NOT NULL,
  `arguments` longtext NOT NULL,
  `command_context` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`command_context`)),
  `status` varchar(255) NOT NULL,
  `attempt_count` int(10) unsigned NOT NULL DEFAULT 0,
  `lease_owner` varchar(255) DEFAULT NULL,
  `lease_expires_at` timestamp(6) NULL DEFAULT NULL,
  `rejection_reason` varchar(255) DEFAULT NULL,
  `rejection_message` text DEFAULT NULL,
  `failure_type` varchar(255) DEFAULT NULL,
  `validation_errors` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`validation_errors`)),
  `approved_at` timestamp(6) NULL DEFAULT NULL,
  `rejected_at` timestamp(6) NULL DEFAULT NULL,
  `failed_at` timestamp(6) NULL DEFAULT NULL,
  `timed_out_at` timestamp(6) NULL DEFAULT NULL,
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `workflow_update_validation_tasks_idempotency_key_unique` (`idempotency_key`),
  KEY `workflow_update_validation_poll_index` (`namespace`,`task_queue`,`status`,`created_at`),
  KEY `workflow_update_validation_tasks_namespace_index` (`namespace`),
  KEY `workflow_update_validation_tasks_workflow_instance_id_index` (`workflow_instance_id`),
  KEY `workflow_update_validation_tasks_workflow_run_id_index` (`workflow_run_id`),
  KEY `workflow_update_validation_tasks_workflow_type_index` (`workflow_type`),
  KEY `workflow_update_validation_tasks_task_queue_index` (`task_queue`),
  KEY `workflow_update_validation_tasks_compatibility_index` (`compatibility`),
  KEY `workflow_update_validation_tasks_update_name_index` (`update_name`),
  KEY `workflow_update_validation_tasks_status_index` (`status`),
  KEY `workflow_update_validation_tasks_lease_owner_index` (`lease_owner`),
  KEY `workflow_update_validation_tasks_lease_expires_at_index` (`lease_expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_worker_build_id_rollouts` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `namespace` varchar(128) NOT NULL,
  `task_queue` varchar(255) NOT NULL,
  `build_id` varchar(255) NOT NULL DEFAULT '',
  `drain_intent` varchar(32) NOT NULL DEFAULT 'active',
  `drained_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `promoted_at` timestamp NULL DEFAULT NULL,
  `rolled_back_at` timestamp NULL DEFAULT NULL,
  `required_compatibility` varchar(255) DEFAULT NULL,
  `recorded_fingerprint` varchar(255) DEFAULT NULL,
  `compatibility_policy` varchar(32) DEFAULT NULL,
  `workflow_types` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`workflow_types`)),
  PRIMARY KEY (`id`),
  UNIQUE KEY `workflow_build_id_rollouts_scope_unique` (`namespace`,`task_queue`,`build_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_worker_compatibility_heartbeats` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `worker_id` varchar(255) NOT NULL,
  `scope_key` varchar(64) NOT NULL,
  `namespace` varchar(255) DEFAULT NULL,
  `host` varchar(255) DEFAULT NULL,
  `process_id` varchar(255) DEFAULT NULL,
  `connection` varchar(255) DEFAULT NULL,
  `queue` varchar(255) DEFAULT NULL,
  `supported` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`supported`)),
  `recorded_at` datetime(6) NOT NULL,
  `expires_at` datetime(6) NOT NULL,
  `created_at` timestamp(6) NULL DEFAULT NULL,
  `updated_at` timestamp(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `workflow_worker_compatibility_heartbeats_scope_unique` (`worker_id`,`scope_key`),
  KEY `workflow_worker_compatibility_heartbeats_namespace_index` (`namespace`),
  KEY `workflow_worker_compatibility_heartbeats_connection_index` (`connection`),
  KEY `workflow_worker_compatibility_heartbeats_queue_index` (`queue`),
  KEY `workflow_worker_compatibility_heartbeats_expires_at_index` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_worker_registrations` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `worker_id` varchar(255) NOT NULL,
  `namespace` varchar(128) NOT NULL,
  `task_queue` varchar(255) NOT NULL,
  `runtime` varchar(32) NOT NULL,
  `sdk_version` varchar(64) DEFAULT NULL,
  `build_id` varchar(255) DEFAULT NULL,
  `supported_workflow_types` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`supported_workflow_types`)),
  `workflow_definition_fingerprints` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`workflow_definition_fingerprints`)),
  `workflow_command_contracts` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`workflow_command_contracts`)),
  `supported_activity_types` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`supported_activity_types`)),
  `capabilities` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`capabilities`)),
  `capability_manifest` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`capability_manifest`)),
  `max_concurrent_workflow_tasks` int(10) unsigned NOT NULL DEFAULT 100,
  `max_concurrent_activity_tasks` int(10) unsigned NOT NULL DEFAULT 100,
  `max_concurrent_worker_sessions` int(10) unsigned NOT NULL DEFAULT 10,
  `available_workflow_slots` int(10) unsigned DEFAULT NULL,
  `available_activity_slots` int(10) unsigned DEFAULT NULL,
  `available_session_slots` int(10) unsigned DEFAULT NULL,
  `process_metrics` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`process_metrics`)),
  `heartbeat_interval_seconds` int(10) unsigned DEFAULT NULL,
  `last_heartbeat_at` timestamp NULL DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'active',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `workflow_worker_registrations_worker_id_namespace_unique` (`worker_id`,`namespace`),
  KEY `workflow_worker_registrations_namespace_task_queue_status_index` (`namespace`,`task_queue`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `workflow_worker_sessions` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `namespace` varchar(128) NOT NULL,
  `session_id` varchar(255) NOT NULL,
  `connection` varchar(255) DEFAULT NULL,
  `queue` varchar(255) DEFAULT NULL,
  `requirements` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`requirements`)),
  `status` varchar(32) NOT NULL DEFAULT 'active',
  `lease_owner` varchar(255) DEFAULT NULL,
  `lease_expires_at` timestamp NULL DEFAULT NULL,
  `ttl_expires_at` timestamp NULL DEFAULT NULL,
  `closed_at` timestamp NULL DEFAULT NULL,
  `failure_reason` varchar(128) DEFAULT NULL,
  `lease_seconds` int(10) unsigned NOT NULL DEFAULT 120,
  `ttl_seconds` int(10) unsigned NOT NULL DEFAULT 1800,
  `max_concurrent_activities` int(10) unsigned NOT NULL DEFAULT 1,
  `create_if_missing` tinyint(1) NOT NULL DEFAULT 1,
  `allow_reacquire_after_failure` tinyint(1) NOT NULL DEFAULT 1,
  `last_heartbeat_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `workflow_worker_sessions_namespace_session_id_unique` (`namespace`,`session_id`),
  KEY `workflow_worker_sessions_namespace_status_index` (`namespace`,`status`),
  KEY `workflow_worker_sessions_namespace_lease_owner_status_index` (`namespace`,`lease_owner`,`status`),
  KEY `workflow_worker_sessions_namespace_queue_status_index` (`namespace`,`queue`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- Native receipts are separate from PHP-owned columns.
CREATE TABLE IF NOT EXISTS dw_task_completions (
    task_id VARCHAR(26) COLLATE utf8mb4_unicode_ci PRIMARY KEY,
    receipt JSON NOT NULL,
    CONSTRAINT dw_task_completions_task FOREIGN KEY(task_id) REFERENCES workflow_tasks(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS dw_poll_receipts (
    namespace VARCHAR(255) NOT NULL,
    worker_id VARCHAR(255) NOT NULL,
    kind VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    request_id VARCHAR(255) NOT NULL,
    task_id VARCHAR(26) COLLATE utf8mb4_unicode_ci NOT NULL,
    attempt BIGINT NOT NULL,
    response JSON NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY(namespace,worker_id,kind,request_id),
    CONSTRAINT dw_poll_receipts_task FOREIGN KEY(task_id) REFERENCES workflow_tasks(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_nopad_bin;
CREATE TABLE IF NOT EXISTS dw_query_cache (
    `key` VARCHAR(64) PRIMARY KEY,
    value LONGTEXT NOT NULL,
    expiration BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
SET FOREIGN_KEY_CHECKS=1;
