-- Native development schema version 2. The PHP relations/indexes below are
-- captured from the image pinned in tests/Fixtures/ServerParity/php-baseline.json.
-- This creates a fresh database; it never converts or adopts a PHP database.
CREATE TABLE "activity_attempts" ("id" varchar not null, "workflow_run_id" varchar not null, "activity_execution_id" varchar not null, "workflow_task_id" varchar, "attempt_number" integer not null, "status" varchar not null, "lease_owner" varchar, "started_at" datetime not null, "last_heartbeat_at" datetime, "lease_expires_at" datetime, "closed_at" datetime, "created_at" datetime, "updated_at" datetime, "worker_attempt_id" varchar, primary key ("id"));
CREATE TABLE "activity_executions" ("id" varchar not null, "workflow_run_id" varchar not null, "sequence" integer not null, "activity_class" varchar not null, "activity_type" varchar not null, "status" varchar not null, "payload_codec" varchar, "arguments" text, "result" text, "exception" text, "connection" varchar, "queue" varchar, "attempt_count" integer not null default '1', "current_attempt_id" varchar, "retry_policy" text, "parallel_group_path" text, "activity_options" text, "schedule_deadline_at" datetime, "close_deadline_at" datetime, "schedule_to_close_deadline_at" datetime, "heartbeat_deadline_at" datetime, "started_at" datetime, "closed_at" datetime, "last_heartbeat_at" datetime, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE TABLE "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE TABLE "jobs" ("id" integer primary key autoincrement not null, "queue" varchar not null, "payload" text not null, "attempts" integer not null, "reserved_at" integer, "available_at" integer not null, "created_at" integer not null);
CREATE TABLE "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
CREATE TABLE "runtime_credentials" ("id" varchar not null, "name" varchar, "subject" varchar not null, "roles" text not null, "tenant" varchar not null, "claims" text, "token_prefix" varchar not null, "token_hash" varchar not null, "expires_at" datetime, "revoked_at" datetime, "rotated_at" datetime, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE TABLE "runtime_external_payload_backup_hold" ("id" integer not null, "owner" varchar, "acquired_at" datetime, "expires_at" datetime, primary key ("id"));
CREATE TABLE "runtime_external_payload_cleanup_stats" ("namespace" varchar not null, "passes_total" integer not null default '0', "deleted_references_total" integer not null default '0', "deleted_backing_objects_total" integer not null default '0', "shared_objects_preserved_total" integer not null default '0', "blocked_outcomes_total" integer not null default '0', "storage_driver_failures_total" integer not null default '0', "last_processed" integer not null default '0', "last_deleted_references" integer not null default '0', "last_deleted_backing_objects" integer not null default '0', "last_shared_objects_preserved" integer not null default '0', "last_blocked_outcomes" integer not null default '0', "last_storage_driver_failures" integer not null default '0', "last_pass_status" varchar, "last_completed_at" datetime, "last_storage_failure_at" datetime, "created_at" datetime, "updated_at" datetime, primary key ("namespace"));
CREATE TABLE "runtime_external_payload_object_locks" ("bucket" integer not null, primary key ("bucket"));
CREATE TABLE "runtime_external_payloads" ("id" varchar not null, "namespace" varchar not null, "storage_uri" text not null, "storage_uri_sha256" varchar not null, "codec" varchar not null, "sha256" varchar not null, "size_bytes" integer not null, "retained_at" datetime, "expires_at" datetime, "last_fetched_at" datetime, "created_at" datetime, "updated_at" datetime, "upload_status" varchar not null default 'ready', primary key ("id"));
CREATE TABLE "runtime_payload_completion_budgets" ("id" varchar not null, "namespace" varchar not null, "context" text not null, "slots" text not null, "objects" text not null, "expires_at" datetime not null, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE TABLE "search_attribute_definitions" ("id" integer primary key autoincrement not null, "namespace" varchar not null, "name" varchar not null, "type" varchar not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE "workflow_child_calls" ("id" integer primary key autoincrement not null, "parent_workflow_run_id" varchar not null, "parent_workflow_instance_id" varchar not null, "sequence" integer not null, "child_workflow_type" varchar not null, "child_workflow_class" varchar not null, "requested_child_id" varchar, "resolved_child_instance_id" varchar, "resolved_child_run_id" varchar, "parent_close_policy" varchar not null default 'abandon', "connection" varchar, "queue" varchar, "compatibility" varchar, "retry_policy" text, "timeout_policy" text, "cancellation_propagation" tinyint(1) not null default '0', "status" varchar not null default 'scheduled', "result_payload_reference" varchar, "failure_reference" varchar, "closed_reason" varchar, "scheduled_at" datetime not null, "started_at" datetime, "closed_at" datetime, "arguments" text, "metadata" text, "created_at" datetime, "updated_at" datetime, foreign key("parent_workflow_run_id") references "workflow_runs"("id") on delete cascade);
CREATE TABLE "workflow_child_projection_repairs" ("workflow_history_event_id" varchar not null, "workflow_run_id" varchar not null, "workflow_task_id" varchar not null, "history_sequence" integer not null, "failure_id" varchar, "failed_child_counted_at" datetime, "created_at" datetime, "updated_at" datetime, primary key ("workflow_history_event_id"));
CREATE TABLE "workflow_commands" ("id" varchar not null, "workflow_instance_id" varchar, "workflow_run_id" varchar, "requested_workflow_run_id" varchar, "resolved_workflow_run_id" varchar, "command_type" varchar not null, "target_scope" varchar not null default 'instance', "source" varchar not null default 'php', "context" text, "request_id" varchar, "status" varchar not null, "outcome" varchar, "workflow_class" varchar, "workflow_type" varchar, "payload_codec" varchar, "payload" text, "rejection_reason" varchar, "command_sequence" integer, "message_sequence" integer, "accepted_at" datetime, "applied_at" datetime, "rejected_at" datetime, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE TABLE "workflow_durable_stream_items" ("id" integer primary key autoincrement not null, "stream_id" integer not null, "namespace" varchar not null, "workflow_run_id" varchar not null, "stream_name" varchar not null, "offset" integer not null, "idempotency_key" varchar, "origin" varchar not null default 'workflow_command', "origin_reference" varchar, "payload" text, "payload_reference" varchar, "payload_codec" varchar, "item_type" varchar, "content_type" varchar, "emitted_at" datetime not null, "created_at" datetime, "updated_at" datetime, foreign key("stream_id") references "workflow_durable_streams"("id") on delete cascade);
CREATE TABLE "workflow_durable_streams" ("id" integer primary key autoincrement not null, "namespace" varchar not null, "workflow_instance_id" varchar not null, "workflow_run_id" varchar not null, "stream_name" varchar not null, "status" varchar not null default 'open', "last_offset" integer not null default '-1', "total_items" integer not null default '0', "retention_seconds" integer, "opened_at" datetime, "last_appended_at" datetime, "closed_at" datetime, "error_reason" varchar, "pending_items" integer not null default '0', "metadata" text, "created_at" datetime, "updated_at" datetime);
CREATE TABLE "workflow_failures" ("id" varchar not null, "workflow_run_id" varchar not null, "source_kind" varchar not null, "source_id" varchar not null, "propagation_kind" varchar not null, "failure_category" varchar, "non_retryable" tinyint(1) not null default '0', "handled" tinyint(1) not null default '0', "exception_class" varchar not null, "message" text not null, "file" text not null, "line" integer, "trace_preview" text, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE TABLE "workflow_history_events" ("id" varchar not null, "workflow_run_id" varchar not null, "sequence" integer not null, "event_type" varchar not null, "payload" text, "workflow_task_id" varchar, "workflow_command_id" varchar, "recorded_at" datetime, "created_at" datetime, "updated_at" datetime, "recorded_at_utc" datetime, primary key ("id"));
CREATE TABLE "workflow_inbound_stream_items" ("id" integer primary key autoincrement not null, "stream_id" integer not null, "namespace" varchar not null, "workflow_instance_id" varchar not null, "stream_name" varchar not null, "message_id" varchar not null, "position" integer not null, "payload_codec" varchar not null, "payload_blob" text not null, "payload_hash" varchar not null, "delivered_run_id" varchar, "workflow_command_id" varchar, "delivered_at" datetime, "consumed_run_id" varchar, "consumed_task_id" varchar, "consumed_at" datetime, "created_at" datetime, "updated_at" datetime, "payload_released_at" datetime, foreign key("stream_id") references "workflow_inbound_streams"("id") on delete cascade);
CREATE TABLE "workflow_inbound_streams" ("id" integer primary key autoincrement not null, "namespace" varchar not null, "workflow_instance_id" varchar not null, "stream_name" varchar not null, "last_position" integer not null default '0', "cursor_position" integer not null default '0', "cursor_checkpoint_run_id" varchar, "waiting_run_id" varchar, "waiting_after_position" integer, "waiting_since" datetime, "duplicate_count" integer not null default '0', "malformed_count" integer not null default '0', "last_input_outcome" varchar, "last_input_message_id" varchar, "last_input_at" datetime, "created_at" datetime, "updated_at" datetime, "cleanup_blocked_at" datetime, "cleanup_blocked_reason" varchar, "cleanup_blocked_run_id" varchar);
CREATE TABLE "workflow_instances" ("id" varchar not null, "workflow_class" varchar not null, "workflow_type" varchar not null, "namespace" varchar, "business_key" varchar, "visibility_labels" text, "memo" text, "execution_timeout_seconds" integer, "current_run_id" varchar, "run_count" integer not null default '0', "last_message_sequence" integer not null default '0', "reserved_at" datetime, "started_at" datetime, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE TABLE "workflow_links" ("id" varchar not null, "link_type" varchar not null, "sequence" integer, "parallel_group_path" text, "parent_workflow_instance_id" varchar not null, "parent_workflow_run_id" varchar not null, "child_workflow_instance_id" varchar not null, "child_workflow_run_id" varchar not null, "is_primary_parent" tinyint(1) not null default '0', "parent_close_policy" varchar not null default 'abandon', "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE TABLE "workflow_memos" ("id" integer primary key autoincrement not null, "workflow_run_id" varchar not null, "workflow_instance_id" varchar not null, "key" varchar not null, "value" text not null, "upserted_at_sequence" integer not null, "inherited_from_parent" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime, "portable_value" text, "portable_value_sequence" integer, foreign key("workflow_run_id") references "workflow_runs"("id") on delete cascade);
CREATE TABLE "workflow_messages" ("id" integer primary key autoincrement not null, "workflow_instance_id" varchar not null, "workflow_run_id" varchar, "direction" varchar not null, "channel" varchar not null, "stream_key" varchar not null, "sequence" integer not null, "source_workflow_instance_id" varchar, "source_workflow_run_id" varchar, "target_workflow_instance_id" varchar, "target_workflow_run_id" varchar, "correlation_id" varchar, "idempotency_key" varchar, "payload_reference" varchar, "consume_state" varchar not null default 'pending', "consumed_at" datetime, "consumed_by_sequence" integer, "expires_at" datetime, "delivery_attempt_count" integer not null default '0', "last_delivery_attempt_at" datetime, "last_delivery_error" text, "metadata" text, "created_at" datetime, "updated_at" datetime, foreign key("workflow_run_id") references "workflow_runs"("id") on delete cascade);
CREATE TABLE "workflow_namespaces" ("id" integer primary key autoincrement not null, "name" varchar not null, "description" varchar, "retention_days" integer default '30', "status" varchar not null default ('active'), "created_at" datetime, "updated_at" datetime, "external_payload_storage" text, "retention_mode" varchar not null default 'bounded');
CREATE TABLE "workflow_run_lineage_entries" ("id" varchar not null, "workflow_run_id" varchar not null, "workflow_instance_id" varchar not null, "direction" varchar not null, "lineage_id" varchar not null, "position" integer not null, "link_type" varchar not null, "child_call_id" varchar, "sequence" integer, "is_primary_parent" tinyint(1) not null default '0', "related_workflow_instance_id" varchar, "related_workflow_run_id" varchar, "related_run_number" integer, "related_workflow_type" varchar, "related_workflow_class" varchar, "status" varchar, "status_bucket" varchar, "closed_reason" varchar, "linked_at" datetime, "payload" text, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE TABLE "workflow_run_summaries" ("id" varchar not null, "workflow_instance_id" varchar not null, "run_number" integer not null, "is_current_run" tinyint(1) not null default '0', "engine_source" varchar not null default 'v2', "projection_schema_version" integer, "class" varchar not null, "workflow_type" varchar not null, "namespace" varchar, "compatibility" varchar, "declared_entry_mode" varchar, "declared_contract_source" varchar, "business_key" varchar, "visibility_labels" text, "status" varchar not null, "status_bucket" varchar not null, "closed_reason" varchar, "connection" varchar, "queue" varchar, "started_at" datetime, "sort_timestamp" datetime, "sort_key" varchar, "closed_at" datetime, "archived_at" datetime, "archive_command_id" varchar, "archive_reason" varchar, "duration_ms" integer, "wait_kind" varchar, "wait_reason" text, "wait_started_at" datetime, "wait_deadline_at" datetime, "open_wait_id" varchar, "resume_source_kind" varchar, "resume_source_id" varchar, "next_task_at" datetime, "liveness_state" varchar, "liveness_reason" text, "repair_blocked_reason" varchar, "repair_attention" tinyint(1) not null default '0', "task_problem" tinyint(1) not null default '0', "next_task_id" varchar, "next_task_type" varchar, "next_task_status" varchar, "next_task_lease_expires_at" datetime, "exception_count" integer not null default '0', "history_event_count" integer not null default '0', "history_size_bytes" integer not null default '0', "continue_as_new_recommended" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime, "history_fan_out" integer not null default '0', "history_budget_pressure" varchar not null default 'ok', primary key ("id"));
CREATE TABLE "workflow_run_timeline_entries" ("id" varchar not null, "workflow_run_id" varchar not null, "workflow_instance_id" varchar not null, "history_event_id" varchar not null, "sequence" integer not null, "type" varchar not null, "kind" varchar not null, "entry_kind" varchar not null default 'point', "source_kind" varchar, "source_id" varchar, "summary" text, "recorded_at" datetime, "command_id" varchar, "command_sequence" integer, "task_id" varchar, "activity_execution_id" varchar, "timer_id" varchar, "failure_id" varchar, "payload" text, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE TABLE "workflow_run_timer_entries" ("id" varchar not null, "workflow_run_id" varchar not null, "workflow_instance_id" varchar not null, "timer_id" varchar not null, "schema_version" integer not null default '1', "position" integer not null, "sequence" integer, "status" varchar not null, "source_status" varchar, "delay_seconds" integer, "fire_at" datetime, "fired_at" datetime, "cancelled_at" datetime, "timer_kind" varchar, "condition_wait_id" varchar, "condition_key" varchar, "condition_definition_fingerprint" varchar, "history_authority" varchar, "history_unsupported_reason" varchar, "payload" text, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE TABLE "workflow_run_timers" ("id" varchar not null, "workflow_run_id" varchar not null, "sequence" integer not null, "status" varchar not null, "delay_seconds" integer not null, "fire_at" datetime not null, "fired_at" datetime, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE TABLE "workflow_run_waits" ("id" varchar not null, "workflow_run_id" varchar not null, "workflow_instance_id" varchar not null, "wait_id" varchar not null, "position" integer not null, "kind" varchar not null, "sequence" integer, "status" varchar not null, "source_status" varchar, "summary" text, "opened_at" datetime, "deadline_at" datetime, "resolved_at" datetime, "target_name" varchar, "target_type" varchar, "task_backed" tinyint(1) not null default '0', "external_only" tinyint(1) not null default '0', "resume_source_kind" varchar, "resume_source_id" varchar, "task_id" varchar, "task_type" varchar, "task_status" varchar, "command_id" varchar, "command_sequence" integer, "command_status" varchar, "command_outcome" varchar, "history_authority" varchar, "history_unsupported_reason" varchar, "payload" text, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE TABLE "workflow_runs" ("id" varchar not null, "workflow_instance_id" varchar not null, "run_number" integer not null, "workflow_class" varchar not null, "workflow_type" varchar not null, "namespace" varchar, "business_key" varchar, "visibility_labels" text, "status" varchar not null, "closed_reason" varchar, "compatibility" varchar, "payload_codec" varchar, "arguments" text, "output" text, "output_payload_codec" varchar, "connection" varchar, "queue" varchar, "sticky_worker_id" varchar, "sticky_until" datetime, "last_history_sequence" integer not null default '0', "last_command_sequence" integer not null default '0', "message_cursor_position" integer not null default '0', "run_timeout_seconds" integer, "execution_deadline_at" datetime, "run_deadline_at" datetime, "started_at" datetime, "closed_at" datetime, "archived_at" datetime, "archive_command_id" varchar, "archive_reason" varchar, "last_progress_at" datetime, "created_at" datetime, "updated_at" datetime, "import_source" varchar, "import_id" varchar, "import_dedupe_key" varchar, "import_contract_version" integer, "imported_at" datetime, "priority" integer not null default '5', "fairness_key" varchar, "fairness_weight" integer not null default '1', "cancellation_request_command_id" varchar, "cancellation_requested_at" datetime, "cancellation_deadline_at" datetime, "cancellation_delivery_sequence" integer, "cancellation_delivered_at" datetime, "details_pruned_at" datetime, "cancellation_scope_recovery_until" datetime, primary key ("id"));
CREATE TABLE "workflow_schedule_history_events" ("id" varchar not null, "workflow_schedule_id" varchar not null, "schedule_id" varchar not null, "namespace" varchar, "sequence" integer not null, "event_type" varchar not null, "payload" text, "workflow_instance_id" varchar, "workflow_run_id" varchar, "recorded_at" datetime, "created_at" datetime, "updated_at" datetime, "occurrence_at_utc" varchar, primary key ("id"));
CREATE TABLE "workflow_schedules" ("id" varchar not null, "schedule_id" varchar not null, "namespace" varchar, "spec" text, "action" text, "status" varchar not null default 'active', "overlap_policy" varchar not null default 'skip', "note" text, "memo" text, "search_attributes" text, "visibility_labels" text, "jitter_seconds" integer not null default '0', "max_runs" integer, "remaining_actions" integer, "fires_count" integer not null default '0', "failures_count" integer not null default '0', "recent_actions" text, "buffered_actions" text, "last_fired_at" datetime, "next_fire_at" datetime, "latest_workflow_instance_id" varchar, "connection" varchar, "queue" varchar, "paused_at" datetime, "deleted_at" datetime, "last_skip_reason" varchar, "last_skipped_at" datetime, "skipped_trigger_count" integer not null default '0', "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE TABLE "workflow_search_attributes" ("id" integer primary key autoincrement not null, "workflow_run_id" varchar not null, "workflow_instance_id" varchar not null, "key" varchar not null, "type" varchar not null, "value_string" text, "value_keyword" varchar, "value_int" integer, "value_float" double, "value_bool" tinyint(1), "value_datetime" datetime, "upserted_at_sequence" integer not null, "inherited_from_parent" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime, "value_keyword_list" text, foreign key("workflow_run_id") references "workflow_runs"("id") on delete cascade);
CREATE TABLE "workflow_service_calls" ("id" varchar not null, "workflow_service_endpoint_id" varchar, "workflow_service_id" varchar, "workflow_service_operation_id" varchar, "namespace" varchar, "endpoint_name" varchar not null, "service_name" varchar not null, "operation_name" varchar not null, "caller_namespace" varchar, "caller_workflow_instance_id" varchar, "caller_workflow_run_id" varchar, "target_namespace" varchar, "linked_workflow_instance_id" varchar, "linked_workflow_run_id" varchar, "linked_workflow_update_id" varchar, "status" varchar not null, "outcome" varchar, "operation_mode" varchar not null, "resolved_binding_kind" varchar, "resolved_target_reference" varchar, "payload_codec" varchar, "input_payload_reference" varchar, "output_payload_reference" varchar, "failure_payload_reference" varchar, "failure_message" text, "idempotency_key" varchar, "deadline_policy" text, "idempotency_policy" text, "cancellation_policy" text, "retry_policy" text, "boundary_policy" text, "metadata" text, "outcome_category" varchar, "outcome_reason" varchar, "outcome_message" text, "outcome_metadata" text, "policy_name" varchar, "retry_after_seconds" integer, "caller_principal_subject" varchar, "caller_principal_method" varchar, "caller_principal_roles" text, "caller_principal_tenant" varchar, "caller_principal_claims" text, "accepted_at" datetime, "started_at" datetime, "completed_at" datetime, "failed_at" datetime, "cancelled_at" datetime, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE TABLE "workflow_service_endpoints" ("id" varchar not null, "namespace" varchar, "endpoint_name" varchar not null, "description" text, "boundary_policy" text, "metadata" text, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE TABLE "workflow_service_operations" ("id" varchar not null, "workflow_service_endpoint_id" varchar not null, "workflow_service_id" varchar not null, "namespace" varchar, "operation_name" varchar not null, "description" text, "operation_mode" varchar not null, "handler_binding_kind" varchar not null, "handler_target_reference" varchar, "handler_binding" text, "deadline_policy" text, "idempotency_policy" text, "cancellation_policy" text, "retry_policy" text, "boundary_policy" text, "metadata" text, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE TABLE "workflow_services" ("id" varchar not null, "workflow_service_endpoint_id" varchar not null, "namespace" varchar, "service_name" varchar not null, "description" text, "boundary_policy" text, "metadata" text, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE TABLE "workflow_signal_records" ("id" varchar not null, "workflow_command_id" varchar not null, "workflow_instance_id" varchar, "workflow_run_id" varchar, "target_scope" varchar not null default 'instance', "requested_workflow_run_id" varchar, "resolved_workflow_run_id" varchar, "signal_name" varchar not null, "signal_wait_id" varchar, "status" varchar not null, "outcome" varchar, "command_sequence" integer, "workflow_sequence" integer, "payload_codec" varchar, "arguments" text, "validation_errors" text, "rejection_reason" varchar, "received_at" datetime, "applied_at" datetime, "rejected_at" datetime, "closed_at" datetime, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE TABLE "workflow_task_poll_cursors" ("namespace" varchar not null, "task_queue" varchar not null, "next_task_kind" varchar not null, "created_at" datetime, "updated_at" datetime, primary key ("namespace", "task_queue"));
CREATE TABLE "workflow_tasks" ("id" varchar not null, "workflow_run_id" varchar not null, "namespace" varchar, "task_type" varchar not null, "status" varchar not null, "compatibility" varchar, "payload" text, "connection" varchar, "queue" varchar, "sticky_worker_id" varchar, "sticky_until" datetime, "sticky_replay_mode" varchar, "sticky_claimed_at" datetime, "available_at" datetime, "leased_at" datetime, "lease_owner" varchar, "lease_expires_at" datetime, "attempt_count" integer not null default '0', "last_dispatch_attempt_at" datetime, "last_dispatched_at" datetime, "last_dispatch_error" text, "last_claim_failed_at" datetime, "last_claim_error" text, "repair_count" integer not null default '0', "repair_available_at" datetime, "last_error" text, "created_at" datetime, "updated_at" datetime, "priority" integer not null default '5', "fairness_key" varchar, "fairness_weight" integer not null default '1', primary key ("id"));
CREATE TABLE "workflow_update_validation_tasks" ("id" varchar not null, "idempotency_key" varchar not null, "namespace" varchar not null, "workflow_instance_id" varchar not null, "workflow_run_id" varchar not null, "workflow_type" varchar not null, "task_queue" varchar not null, "compatibility" varchar, "workflow_definition_fingerprint" varchar, "update_name" varchar not null, "request_id" varchar not null, "input_hash" varchar not null, "payload_codec" varchar not null, "arguments" text not null, "command_context" text, "status" varchar not null, "attempt_count" integer not null default '0', "lease_owner" varchar, "lease_expires_at" datetime, "rejection_reason" varchar, "rejection_message" text, "failure_type" varchar, "validation_errors" text, "approved_at" datetime, "rejected_at" datetime, "failed_at" datetime, "timed_out_at" datetime, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE TABLE "workflow_updates" ("id" varchar not null, "workflow_command_id" varchar not null, "workflow_instance_id" varchar, "workflow_run_id" varchar, "target_scope" varchar not null default 'instance', "requested_workflow_run_id" varchar, "resolved_workflow_run_id" varchar, "update_name" varchar not null, "status" varchar not null, "outcome" varchar, "command_sequence" integer, "workflow_sequence" integer, "payload_codec" varchar, "arguments" text, "result" text, "validation_errors" text, "rejection_reason" varchar, "failure_id" varchar, "failure_message" text, "accepted_at" datetime, "applied_at" datetime, "rejected_at" datetime, "closed_at" datetime, "created_at" datetime, "updated_at" datetime, primary key ("id"));
CREATE TABLE "workflow_worker_build_id_rollouts" ("id" integer primary key autoincrement not null, "namespace" varchar not null, "task_queue" varchar not null, "build_id" varchar not null default '', "drain_intent" varchar not null default 'active', "drained_at" datetime, "created_at" datetime, "updated_at" datetime, "promoted_at" datetime, "rolled_back_at" datetime, "required_compatibility" varchar, "recorded_fingerprint" varchar, "compatibility_policy" varchar, "workflow_types" text);
CREATE TABLE "workflow_worker_compatibility_heartbeats" ("id" integer primary key autoincrement not null, "worker_id" varchar not null, "scope_key" varchar not null, "namespace" varchar, "host" varchar, "process_id" varchar, "connection" varchar, "queue" varchar, "supported" text not null, "recorded_at" datetime not null, "expires_at" datetime not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE "workflow_worker_registrations" ("id" integer primary key autoincrement not null, "worker_id" varchar not null, "namespace" varchar not null, "task_queue" varchar not null, "runtime" varchar not null, "sdk_version" varchar, "build_id" varchar, "supported_workflow_types" text, "workflow_definition_fingerprints" text, "supported_activity_types" text, "max_concurrent_workflow_tasks" integer not null default '100', "max_concurrent_activity_tasks" integer not null default '100', "last_heartbeat_at" datetime, "status" varchar not null default 'active', "created_at" datetime, "updated_at" datetime, "capabilities" text, "max_concurrent_worker_sessions" integer not null default '10', "available_workflow_slots" integer, "available_activity_slots" integer, "available_session_slots" integer, "process_metrics" text, "heartbeat_interval_seconds" integer, "workflow_command_contracts" text, "capability_manifest" text);
CREATE TABLE "workflow_worker_sessions" ("id" integer primary key autoincrement not null, "namespace" varchar not null, "session_id" varchar not null, "connection" varchar, "queue" varchar, "requirements" text, "status" varchar not null default 'active', "lease_owner" varchar, "lease_expires_at" datetime, "ttl_expires_at" datetime, "closed_at" datetime, "failure_reason" varchar, "lease_seconds" integer not null default '120', "ttl_seconds" integer not null default '1800', "max_concurrent_activities" integer not null default '1', "create_if_missing" tinyint(1) not null default '1', "allow_reacquire_after_failure" tinyint(1) not null default '1', "last_heartbeat_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "activity_attempts_activity_execution_id_attempt_number_unique" on "activity_attempts" ("activity_execution_id", "attempt_number");
CREATE INDEX "activity_attempts_activity_execution_id_index" on "activity_attempts" ("activity_execution_id");
CREATE INDEX "activity_attempts_workflow_run_id_index" on "activity_attempts" ("workflow_run_id");
CREATE INDEX "activity_attempts_workflow_task_id_index" on "activity_attempts" ("workflow_task_id");
CREATE INDEX "activity_exec_prom_metrics_series_idx" on "activity_executions" ("workflow_run_id", "queue", "activity_type");
CREATE INDEX "activity_executions_workflow_run_id_index" on "activity_executions" ("workflow_run_id");
CREATE UNIQUE INDEX "activity_executions_workflow_run_id_sequence_unique" on "activity_executions" ("workflow_run_id", "sequence");
CREATE INDEX "child_calls_child_parent" on "workflow_child_calls" ("resolved_child_instance_id", "parent_workflow_run_id");
CREATE INDEX "child_calls_parent_seq" on "workflow_child_calls" ("parent_workflow_run_id", "sequence");
CREATE INDEX "child_calls_parent_status" on "workflow_child_calls" ("parent_workflow_run_id", "status");
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE INDEX "jobs_queue_index" on "jobs" ("queue");
CREATE INDEX "runtime_credentials_expires_at_index" on "runtime_credentials" ("expires_at");
CREATE INDEX "runtime_credentials_revoked_at_index" on "runtime_credentials" ("revoked_at");
CREATE INDEX "runtime_credentials_tenant_index" on "runtime_credentials" ("tenant");
CREATE UNIQUE INDEX "runtime_credentials_token_hash_unique" on "runtime_credentials" ("token_hash");
CREATE INDEX "runtime_external_payloads_expires_at_index" on "runtime_external_payloads" ("expires_at");
CREATE INDEX "runtime_external_payloads_namespace_index" on "runtime_external_payloads" ("namespace");
CREATE UNIQUE INDEX "runtime_external_payloads_namespace_uri_unique" on "runtime_external_payloads" ("namespace", "storage_uri_sha256");
CREATE INDEX "runtime_external_payloads_reclamation_idx" on "runtime_external_payloads" ("retained_at", "expires_at", "upload_status");
CREATE INDEX "runtime_payload_completion_budgets_expires_at_index" on "runtime_payload_completion_budgets" ("expires_at");
CREATE INDEX "runtime_payload_completion_budgets_namespace_index" on "runtime_payload_completion_budgets" ("namespace");
CREATE INDEX "search_attribute_definitions_namespace_index" on "search_attribute_definitions" ("namespace");
CREATE UNIQUE INDEX "search_attribute_definitions_namespace_name_unique" on "search_attribute_definitions" ("namespace", "name");
CREATE UNIQUE INDEX "wf_durable_stream_items_idempotency_unique" on "workflow_durable_stream_items" ("stream_id", "idempotency_key");
CREATE INDEX "wf_durable_stream_items_run_name_offset_idx" on "workflow_durable_stream_items" ("workflow_run_id", "stream_name", "offset");
CREATE UNIQUE INDEX "wf_durable_stream_items_stream_offset_unique" on "workflow_durable_stream_items" ("stream_id", "offset");
CREATE INDEX "wf_durable_streams_ns_instance_name_idx" on "workflow_durable_streams" ("namespace", "workflow_instance_id", "stream_name");
CREATE INDEX "wf_durable_streams_ns_status_idx" on "workflow_durable_streams" ("namespace", "status");
CREATE UNIQUE INDEX "wf_durable_streams_run_name_unique" on "workflow_durable_streams" ("workflow_run_id", "stream_name");
CREATE INDEX "wf_inbound_items_ns_instance_name_position_idx" on "workflow_inbound_stream_items" ("namespace", "workflow_instance_id", "stream_name", "position");
CREATE UNIQUE INDEX "wf_inbound_items_stream_message_unique" on "workflow_inbound_stream_items" ("stream_id", "message_id");
CREATE UNIQUE INDEX "wf_inbound_items_stream_position_unique" on "workflow_inbound_stream_items" ("stream_id", "position");
CREATE UNIQUE INDEX "wf_inbound_streams_ns_instance_name_unique" on "workflow_inbound_streams" ("namespace", "workflow_instance_id", "stream_name");
CREATE INDEX "wf_msgs_instance_stream_seq" on "workflow_messages" ("workflow_instance_id", "stream_key", "sequence");
CREATE INDEX "wf_msgs_run_dir_state" on "workflow_messages" ("workflow_run_id", "direction", "consume_state");
CREATE INDEX "wf_msgs_stream_seq_state" on "workflow_messages" ("stream_key", "sequence", "consume_state");
CREATE UNIQUE INDEX "wf_msgs_stream_seq_unique" on "workflow_messages" ("workflow_instance_id", "stream_key", "sequence");
CREATE INDEX "wf_msgs_target_state" on "workflow_messages" ("target_workflow_instance_id", "consume_state");
CREATE INDEX "wf_schedule_history_event_recorded_idx" on "workflow_schedule_history_events" ("event_type", "recorded_at");
CREATE INDEX "wf_schedule_history_instance_idx" on "workflow_schedule_history_events" ("workflow_instance_id");
CREATE INDEX "wf_schedule_history_namespace_idx" on "workflow_schedule_history_events" ("namespace");
CREATE INDEX "wf_schedule_history_namespace_schedule_idx" on "workflow_schedule_history_events" ("namespace", "schedule_id");
CREATE INDEX "wf_schedule_history_occurrence_idx" on "workflow_schedule_history_events" ("workflow_schedule_id", "event_type", "occurrence_at_utc");
CREATE INDEX "wf_schedule_history_run_idx" on "workflow_schedule_history_events" ("workflow_run_id");
CREATE INDEX "wf_schedule_history_schedule_idx" on "workflow_schedule_history_events" ("schedule_id");
CREATE UNIQUE INDEX "wf_schedule_history_schedule_sequence_unique" on "workflow_schedule_history_events" ("workflow_schedule_id", "sequence");
CREATE INDEX "wf_schedule_history_workflow_schedule_idx" on "workflow_schedule_history_events" ("workflow_schedule_id");
CREATE INDEX "wf_service_calls_accepted_at_idx" on "workflow_service_calls" ("accepted_at");
CREATE INDEX "wf_service_calls_binding_kind_idx" on "workflow_service_calls" ("resolved_binding_kind");
CREATE INDEX "wf_service_calls_caller_instance_idx" on "workflow_service_calls" ("caller_workflow_instance_id");
CREATE INDEX "wf_service_calls_caller_namespace_idx" on "workflow_service_calls" ("caller_namespace");
CREATE INDEX "wf_service_calls_caller_outcome_idx" on "workflow_service_calls" ("caller_namespace", "outcome");
CREATE INDEX "wf_service_calls_caller_run_idx" on "workflow_service_calls" ("caller_workflow_run_id");
CREATE INDEX "wf_service_calls_caller_status_idx" on "workflow_service_calls" ("caller_namespace", "status");
CREATE INDEX "wf_service_calls_endpoint_idx" on "workflow_service_calls" ("workflow_service_endpoint_id");
CREATE INDEX "wf_service_calls_idempotency_idx" on "workflow_service_calls" ("idempotency_key");
CREATE INDEX "wf_service_calls_linked_instance_idx" on "workflow_service_calls" ("linked_workflow_instance_id");
CREATE INDEX "wf_service_calls_linked_run_idx" on "workflow_service_calls" ("linked_workflow_run_id");
CREATE INDEX "wf_service_calls_linked_update_idx" on "workflow_service_calls" ("linked_workflow_update_id");
CREATE INDEX "wf_service_calls_mode_idx" on "workflow_service_calls" ("operation_mode");
CREATE INDEX "wf_service_calls_namespace_idx" on "workflow_service_calls" ("namespace");
CREATE INDEX "wf_service_calls_namespace_outcome_idx" on "workflow_service_calls" ("namespace", "outcome");
CREATE INDEX "wf_service_calls_namespace_status_idx" on "workflow_service_calls" ("namespace", "status");
CREATE INDEX "wf_service_calls_operation_idx" on "workflow_service_calls" ("workflow_service_operation_id");
CREATE INDEX "wf_service_calls_outcome_category_idx" on "workflow_service_calls" ("outcome_category");
CREATE INDEX "wf_service_calls_outcome_idx" on "workflow_service_calls" ("outcome");
CREATE INDEX "wf_service_calls_policy_idx" on "workflow_service_calls" ("policy_name");
CREATE INDEX "wf_service_calls_principal_subject_idx" on "workflow_service_calls" ("caller_principal_subject");
CREATE INDEX "wf_service_calls_service_idx" on "workflow_service_calls" ("workflow_service_id");
CREATE INDEX "wf_service_calls_status_idx" on "workflow_service_calls" ("status");
CREATE INDEX "wf_service_calls_target_namespace_idx" on "workflow_service_calls" ("target_namespace");
CREATE INDEX "wf_service_calls_target_outcome_idx" on "workflow_service_calls" ("target_namespace", "outcome");
CREATE INDEX "wf_service_calls_target_status_idx" on "workflow_service_calls" ("target_namespace", "status");
CREATE INDEX "wf_service_endpoints_name_idx" on "workflow_service_endpoints" ("endpoint_name");
CREATE INDEX "wf_service_endpoints_namespace_idx" on "workflow_service_endpoints" ("namespace");
CREATE UNIQUE INDEX "wf_service_endpoints_namespace_name_unique" on "workflow_service_endpoints" ("namespace", "endpoint_name");
CREATE INDEX "wf_service_ops_binding_kind_idx" on "workflow_service_operations" ("handler_binding_kind");
CREATE INDEX "wf_service_ops_endpoint_idx" on "workflow_service_operations" ("workflow_service_endpoint_id");
CREATE INDEX "wf_service_ops_mode_idx" on "workflow_service_operations" ("operation_mode");
CREATE INDEX "wf_service_ops_name_idx" on "workflow_service_operations" ("operation_name");
CREATE INDEX "wf_service_ops_namespace_idx" on "workflow_service_operations" ("namespace");
CREATE INDEX "wf_service_ops_namespace_name_idx" on "workflow_service_operations" ("namespace", "operation_name");
CREATE UNIQUE INDEX "wf_service_ops_namespace_service_name_unique" on "workflow_service_operations" ("namespace", "workflow_service_id", "operation_name");
CREATE INDEX "wf_service_ops_service_idx" on "workflow_service_operations" ("workflow_service_id");
CREATE INDEX "wf_services_endpoint_idx" on "workflow_services" ("workflow_service_endpoint_id");
CREATE INDEX "wf_services_name_idx" on "workflow_services" ("service_name");
CREATE UNIQUE INDEX "wf_services_namespace_endpoint_name_unique" on "workflow_services" ("namespace", "workflow_service_endpoint_id", "service_name");
CREATE INDEX "wf_services_namespace_idx" on "workflow_services" ("namespace");
CREATE INDEX "wf_services_namespace_name_idx" on "workflow_services" ("namespace", "service_name");
CREATE INDEX "wfrs_decl_contract_source_idx" on "workflow_run_summaries" ("declared_contract_source");
CREATE INDEX "wfrs_decl_entry_mode_idx" on "workflow_run_summaries" ("declared_entry_mode");
CREATE INDEX "wfrs_namespace_sort_idx" on "workflow_run_summaries" ("namespace", "sort_timestamp", "id");
CREATE INDEX "wfrs_namespace_status_sort_idx" on "workflow_run_summaries" ("namespace", "status_bucket", "sort_timestamp", "id");
CREATE INDEX "wfrs_namespace_type_sort_idx" on "workflow_run_summaries" ("namespace", "workflow_type", "sort_timestamp", "id");
CREATE INDEX "wfrs_prom_metrics_series_idx" on "workflow_run_summaries" ("namespace", "queue", "workflow_type");
CREATE UNIQUE INDEX "workflow_build_id_rollouts_scope_unique" on "workflow_worker_build_id_rollouts" ("namespace", "task_queue", "build_id");
CREATE INDEX "workflow_child_calls_parent_workflow_instance_id_index" on "workflow_child_calls" ("parent_workflow_instance_id");
CREATE INDEX "workflow_child_calls_parent_workflow_run_id_index" on "workflow_child_calls" ("parent_workflow_run_id");
CREATE INDEX "workflow_child_calls_resolved_child_instance_id_index" on "workflow_child_calls" ("resolved_child_instance_id");
CREATE INDEX "workflow_child_calls_resolved_child_run_id_index" on "workflow_child_calls" ("resolved_child_run_id");
CREATE INDEX "workflow_child_calls_sequence_index" on "workflow_child_calls" ("sequence");
CREATE INDEX "workflow_child_calls_status_index" on "workflow_child_calls" ("status");
CREATE INDEX "workflow_child_projection_repairs_drain_idx" on "workflow_child_projection_repairs" ("workflow_run_id", "workflow_task_id", "history_sequence");
CREATE INDEX "workflow_child_projection_repairs_failure_idx" on "workflow_child_projection_repairs" ("workflow_run_id", "failure_id");
CREATE INDEX "workflow_commands_command_sequence_index" on "workflow_commands" ("command_sequence");
CREATE INDEX "workflow_commands_command_type_index" on "workflow_commands" ("command_type");
CREATE UNIQUE INDEX "workflow_commands_request_lookup" on "workflow_commands" ("workflow_instance_id", "command_type", "request_id");
CREATE INDEX "workflow_commands_requested_workflow_run_id_index" on "workflow_commands" ("requested_workflow_run_id");
CREATE INDEX "workflow_commands_resolved_workflow_run_id_index" on "workflow_commands" ("resolved_workflow_run_id");
CREATE INDEX "workflow_commands_source_index" on "workflow_commands" ("source");
CREATE INDEX "workflow_commands_status_index" on "workflow_commands" ("status");
CREATE INDEX "workflow_commands_workflow_instance_id_index" on "workflow_commands" ("workflow_instance_id");
CREATE INDEX "workflow_commands_workflow_run_id_index" on "workflow_commands" ("workflow_run_id");
CREATE INDEX "workflow_durable_stream_items_namespace_index" on "workflow_durable_stream_items" ("namespace");
CREATE INDEX "workflow_durable_stream_items_workflow_run_id_index" on "workflow_durable_stream_items" ("workflow_run_id");
CREATE INDEX "workflow_durable_streams_namespace_index" on "workflow_durable_streams" ("namespace");
CREATE INDEX "workflow_durable_streams_status_index" on "workflow_durable_streams" ("status");
CREATE INDEX "workflow_durable_streams_workflow_instance_id_index" on "workflow_durable_streams" ("workflow_instance_id");
CREATE INDEX "workflow_durable_streams_workflow_run_id_index" on "workflow_durable_streams" ("workflow_run_id");
CREATE INDEX "workflow_failures_failure_category_index" on "workflow_failures" ("failure_category");
CREATE INDEX "workflow_failures_source_kind_source_id_index" on "workflow_failures" ("source_kind", "source_id");
CREATE INDEX "workflow_failures_workflow_run_id_index" on "workflow_failures" ("workflow_run_id");
CREATE INDEX "workflow_history_events_workflow_command_id_index" on "workflow_history_events" ("workflow_command_id");
CREATE INDEX "workflow_history_events_workflow_run_id_index" on "workflow_history_events" ("workflow_run_id");
CREATE UNIQUE INDEX "workflow_history_events_workflow_run_id_sequence_unique" on "workflow_history_events" ("workflow_run_id", "sequence");
CREATE INDEX "workflow_history_events_workflow_task_id_index" on "workflow_history_events" ("workflow_task_id");
CREATE INDEX "workflow_inbound_stream_items_consumed_run_id_index" on "workflow_inbound_stream_items" ("consumed_run_id");
CREATE INDEX "workflow_inbound_stream_items_consumed_task_id_index" on "workflow_inbound_stream_items" ("consumed_task_id");
CREATE INDEX "workflow_inbound_stream_items_delivered_run_id_index" on "workflow_inbound_stream_items" ("delivered_run_id");
CREATE INDEX "workflow_inbound_stream_items_namespace_index" on "workflow_inbound_stream_items" ("namespace");
CREATE INDEX "workflow_inbound_stream_items_payload_released_at_index" on "workflow_inbound_stream_items" ("payload_released_at");
CREATE INDEX "workflow_inbound_stream_items_workflow_command_id_index" on "workflow_inbound_stream_items" ("workflow_command_id");
CREATE INDEX "workflow_inbound_stream_items_workflow_instance_id_index" on "workflow_inbound_stream_items" ("workflow_instance_id");
CREATE INDEX "workflow_inbound_streams_cleanup_blocked_run_id_index" on "workflow_inbound_streams" ("cleanup_blocked_run_id");
CREATE INDEX "workflow_inbound_streams_cursor_checkpoint_run_id_index" on "workflow_inbound_streams" ("cursor_checkpoint_run_id");
CREATE INDEX "workflow_inbound_streams_namespace_index" on "workflow_inbound_streams" ("namespace");
CREATE INDEX "workflow_inbound_streams_waiting_run_id_index" on "workflow_inbound_streams" ("waiting_run_id");
CREATE INDEX "workflow_inbound_streams_workflow_instance_id_index" on "workflow_inbound_streams" ("workflow_instance_id");
CREATE INDEX "workflow_instances_business_key_index" on "workflow_instances" ("business_key");
CREATE INDEX "workflow_instances_current_run_id_index" on "workflow_instances" ("current_run_id");
CREATE INDEX "workflow_instances_namespace_index" on "workflow_instances" ("namespace");
CREATE INDEX "workflow_links_child_workflow_instance_id_index" on "workflow_links" ("child_workflow_instance_id");
CREATE INDEX "workflow_links_child_workflow_run_id_index" on "workflow_links" ("child_workflow_run_id");
CREATE UNIQUE INDEX "workflow_links_parent_child_type_unique" on "workflow_links" ("parent_workflow_run_id", "child_workflow_run_id", "link_type");
CREATE INDEX "workflow_links_parent_sequence_type_index" on "workflow_links" ("parent_workflow_run_id", "sequence", "link_type");
CREATE INDEX "workflow_links_parent_workflow_instance_id_index" on "workflow_links" ("parent_workflow_instance_id");
CREATE INDEX "workflow_links_parent_workflow_run_id_index" on "workflow_links" ("parent_workflow_run_id");
CREATE INDEX "workflow_memos_instance_key" on "workflow_memos" ("workflow_instance_id", "key");
CREATE UNIQUE INDEX "workflow_memos_run_key_unique" on "workflow_memos" ("workflow_run_id", "key");
CREATE INDEX "workflow_messages_channel_index" on "workflow_messages" ("channel");
CREATE INDEX "workflow_messages_consume_state_index" on "workflow_messages" ("consume_state");
CREATE INDEX "workflow_messages_correlation_id_index" on "workflow_messages" ("correlation_id");
CREATE INDEX "workflow_messages_direction_index" on "workflow_messages" ("direction");
CREATE INDEX "workflow_messages_idempotency_key_index" on "workflow_messages" ("idempotency_key");
CREATE INDEX "workflow_messages_sequence_index" on "workflow_messages" ("sequence");
CREATE INDEX "workflow_messages_source_workflow_instance_id_index" on "workflow_messages" ("source_workflow_instance_id");
CREATE INDEX "workflow_messages_stream_key_index" on "workflow_messages" ("stream_key");
CREATE INDEX "workflow_messages_target_workflow_instance_id_index" on "workflow_messages" ("target_workflow_instance_id");
CREATE INDEX "workflow_messages_workflow_instance_id_index" on "workflow_messages" ("workflow_instance_id");
CREATE INDEX "workflow_messages_workflow_run_id_index" on "workflow_messages" ("workflow_run_id");
CREATE UNIQUE INDEX "workflow_namespaces_name_unique" on "workflow_namespaces" ("name");
CREATE INDEX "workflow_run_lineage_entries_child_call_id_index" on "workflow_run_lineage_entries" ("child_call_id");
CREATE INDEX "workflow_run_lineage_entries_closed_reason_index" on "workflow_run_lineage_entries" ("closed_reason");
CREATE INDEX "workflow_run_lineage_entries_direction_index" on "workflow_run_lineage_entries" ("direction");
CREATE INDEX "workflow_run_lineage_entries_is_primary_parent_index" on "workflow_run_lineage_entries" ("is_primary_parent");
CREATE INDEX "workflow_run_lineage_entries_link_type_index" on "workflow_run_lineage_entries" ("link_type");
CREATE INDEX "workflow_run_lineage_entries_linked_at_index" on "workflow_run_lineage_entries" ("linked_at");
CREATE INDEX "workflow_run_lineage_entries_related_workflow_instance_id_index" on "workflow_run_lineage_entries" ("related_workflow_instance_id");
CREATE INDEX "workflow_run_lineage_entries_related_workflow_run_id_index" on "workflow_run_lineage_entries" ("related_workflow_run_id");
CREATE INDEX "workflow_run_lineage_entries_related_workflow_type_index" on "workflow_run_lineage_entries" ("related_workflow_type");
CREATE INDEX "workflow_run_lineage_entries_sequence_index" on "workflow_run_lineage_entries" ("sequence");
CREATE INDEX "workflow_run_lineage_entries_status_bucket_index" on "workflow_run_lineage_entries" ("status_bucket");
CREATE INDEX "workflow_run_lineage_entries_status_index" on "workflow_run_lineage_entries" ("status");
CREATE INDEX "workflow_run_lineage_entries_workflow_instance_id_index" on "workflow_run_lineage_entries" ("workflow_instance_id");
CREATE INDEX "workflow_run_lineage_entries_workflow_run_id_index" on "workflow_run_lineage_entries" ("workflow_run_id");
CREATE INDEX "workflow_run_lineage_instance_direction_type_index" on "workflow_run_lineage_entries" ("workflow_instance_id", "direction", "link_type");
CREATE UNIQUE INDEX "workflow_run_lineage_run_direction_lineage_unique" on "workflow_run_lineage_entries" ("workflow_run_id", "direction", "lineage_id");
CREATE INDEX "workflow_run_lineage_run_direction_position_index" on "workflow_run_lineage_entries" ("workflow_run_id", "direction", "position");
CREATE INDEX "workflow_run_summaries_archive_command_id_index" on "workflow_run_summaries" ("archive_command_id");
CREATE INDEX "workflow_run_summaries_archived_at_index" on "workflow_run_summaries" ("archived_at");
CREATE INDEX "workflow_run_summaries_business_key_index" on "workflow_run_summaries" ("business_key");
CREATE INDEX "workflow_run_summaries_continue_as_new_recommended_index" on "workflow_run_summaries" ("continue_as_new_recommended");
CREATE INDEX "workflow_run_summaries_history_budget_pressure_index" on "workflow_run_summaries" ("history_budget_pressure");
CREATE INDEX "workflow_run_summaries_is_current_run_index" on "workflow_run_summaries" ("is_current_run");
CREATE INDEX "workflow_run_summaries_namespace_index" on "workflow_run_summaries" ("namespace");
CREATE INDEX "workflow_run_summaries_projection_schema_version_index" on "workflow_run_summaries" ("projection_schema_version");
CREATE INDEX "workflow_run_summaries_repair_attention_index" on "workflow_run_summaries" ("repair_attention");
CREATE INDEX "workflow_run_summaries_repair_blocked_reason_index" on "workflow_run_summaries" ("repair_blocked_reason");
CREATE INDEX "workflow_run_summaries_sort_key_index" on "workflow_run_summaries" ("sort_key");
CREATE INDEX "workflow_run_summaries_sort_order_index" on "workflow_run_summaries" ("sort_timestamp", "id");
CREATE INDEX "workflow_run_summaries_status_bucket_index" on "workflow_run_summaries" ("status_bucket");
CREATE INDEX "workflow_run_summaries_status_bucket_started_at_index" on "workflow_run_summaries" ("status_bucket", "started_at");
CREATE INDEX "workflow_run_summaries_status_index" on "workflow_run_summaries" ("status");
CREATE INDEX "workflow_run_summaries_workflow_instance_id_index" on "workflow_run_summaries" ("workflow_instance_id");
CREATE INDEX "workflow_run_timeline_entries_activity_execution_id_index" on "workflow_run_timeline_entries" ("activity_execution_id");
CREATE INDEX "workflow_run_timeline_entries_command_id_index" on "workflow_run_timeline_entries" ("command_id");
CREATE INDEX "workflow_run_timeline_entries_command_sequence_index" on "workflow_run_timeline_entries" ("command_sequence");
CREATE INDEX "workflow_run_timeline_entries_failure_id_index" on "workflow_run_timeline_entries" ("failure_id");
CREATE INDEX "workflow_run_timeline_entries_history_event_id_index" on "workflow_run_timeline_entries" ("history_event_id");
CREATE INDEX "workflow_run_timeline_entries_kind_index" on "workflow_run_timeline_entries" ("kind");
CREATE INDEX "workflow_run_timeline_entries_recorded_at_index" on "workflow_run_timeline_entries" ("recorded_at");
CREATE INDEX "workflow_run_timeline_entries_sequence_index" on "workflow_run_timeline_entries" ("sequence");
CREATE INDEX "workflow_run_timeline_entries_source_id_index" on "workflow_run_timeline_entries" ("source_id");
CREATE INDEX "workflow_run_timeline_entries_source_kind_index" on "workflow_run_timeline_entries" ("source_kind");
CREATE INDEX "workflow_run_timeline_entries_task_id_index" on "workflow_run_timeline_entries" ("task_id");
CREATE INDEX "workflow_run_timeline_entries_timer_id_index" on "workflow_run_timeline_entries" ("timer_id");
CREATE INDEX "workflow_run_timeline_entries_type_index" on "workflow_run_timeline_entries" ("type");
CREATE INDEX "workflow_run_timeline_entries_workflow_instance_id_index" on "workflow_run_timeline_entries" ("workflow_instance_id");
CREATE INDEX "workflow_run_timeline_entries_workflow_run_id_index" on "workflow_run_timeline_entries" ("workflow_run_id");
CREATE INDEX "workflow_run_timeline_instance_kind_recorded_index" on "workflow_run_timeline_entries" ("workflow_instance_id", "kind", "recorded_at");
CREATE UNIQUE INDEX "workflow_run_timeline_run_event_unique" on "workflow_run_timeline_entries" ("workflow_run_id", "history_event_id");
CREATE INDEX "workflow_run_timeline_run_sequence_index" on "workflow_run_timeline_entries" ("workflow_run_id", "sequence");
CREATE INDEX "workflow_run_timer_entries_condition_key_index" on "workflow_run_timer_entries" ("condition_key");
CREATE INDEX "workflow_run_timer_entries_condition_wait_id_index" on "workflow_run_timer_entries" ("condition_wait_id");
CREATE INDEX "workflow_run_timer_entries_history_authority_index" on "workflow_run_timer_entries" ("history_authority");
CREATE INDEX "workflow_run_timer_entries_instance_kind_status_index" on "workflow_run_timer_entries" ("workflow_instance_id", "timer_kind", "status");
CREATE INDEX "workflow_run_timer_entries_run_status_position_index" on "workflow_run_timer_entries" ("workflow_run_id", "status", "position");
CREATE UNIQUE INDEX "workflow_run_timer_entries_run_timer_unique" on "workflow_run_timer_entries" ("workflow_run_id", "timer_id");
CREATE INDEX "workflow_run_timer_entries_sequence_index" on "workflow_run_timer_entries" ("sequence");
CREATE INDEX "workflow_run_timer_entries_source_status_index" on "workflow_run_timer_entries" ("source_status");
CREATE INDEX "workflow_run_timer_entries_status_index" on "workflow_run_timer_entries" ("status");
CREATE INDEX "workflow_run_timer_entries_timer_kind_index" on "workflow_run_timer_entries" ("timer_kind");
CREATE INDEX "workflow_run_timer_entries_workflow_instance_id_index" on "workflow_run_timer_entries" ("workflow_instance_id");
CREATE INDEX "workflow_run_timer_entries_workflow_run_id_index" on "workflow_run_timer_entries" ("workflow_run_id");
CREATE INDEX "workflow_run_timers_status_fire_at_index" on "workflow_run_timers" ("status", "fire_at");
CREATE INDEX "workflow_run_timers_workflow_run_id_index" on "workflow_run_timers" ("workflow_run_id");
CREATE UNIQUE INDEX "workflow_run_timers_workflow_run_id_sequence_unique" on "workflow_run_timers" ("workflow_run_id", "sequence");
CREATE INDEX "workflow_run_waits_command_id_index" on "workflow_run_waits" ("command_id");
CREATE INDEX "workflow_run_waits_history_authority_index" on "workflow_run_waits" ("history_authority");
CREATE INDEX "workflow_run_waits_instance_kind_status_index" on "workflow_run_waits" ("workflow_instance_id", "kind", "status");
CREATE INDEX "workflow_run_waits_kind_index" on "workflow_run_waits" ("kind");
CREATE INDEX "workflow_run_waits_resume_source_id_index" on "workflow_run_waits" ("resume_source_id");
CREATE INDEX "workflow_run_waits_resume_source_kind_index" on "workflow_run_waits" ("resume_source_kind");
CREATE INDEX "workflow_run_waits_run_status_position_index" on "workflow_run_waits" ("workflow_run_id", "status", "position");
CREATE UNIQUE INDEX "workflow_run_waits_run_wait_unique" on "workflow_run_waits" ("workflow_run_id", "wait_id");
CREATE INDEX "workflow_run_waits_sequence_index" on "workflow_run_waits" ("sequence");
CREATE INDEX "workflow_run_waits_source_status_index" on "workflow_run_waits" ("source_status");
CREATE INDEX "workflow_run_waits_status_index" on "workflow_run_waits" ("status");
CREATE INDEX "workflow_run_waits_target_name_index" on "workflow_run_waits" ("target_name");
CREATE INDEX "workflow_run_waits_task_backed_index" on "workflow_run_waits" ("task_backed");
CREATE INDEX "workflow_run_waits_task_id_index" on "workflow_run_waits" ("task_id");
CREATE INDEX "workflow_run_waits_workflow_instance_id_index" on "workflow_run_waits" ("workflow_instance_id");
CREATE INDEX "workflow_run_waits_workflow_run_id_index" on "workflow_run_waits" ("workflow_run_id");
CREATE INDEX "workflow_runs_archive_command_id_index" on "workflow_runs" ("archive_command_id");
CREATE INDEX "workflow_runs_archived_at_index" on "workflow_runs" ("archived_at");
CREATE INDEX "workflow_runs_business_key_index" on "workflow_runs" ("business_key");
CREATE INDEX "workflow_runs_cancellation_request_command_id_index" on "workflow_runs" ("cancellation_request_command_id");
CREATE INDEX "workflow_runs_import_dedupe_key_index" on "workflow_runs" ("import_dedupe_key");
CREATE INDEX "workflow_runs_import_id_index" on "workflow_runs" ("import_id");
CREATE INDEX "workflow_runs_import_source_index" on "workflow_runs" ("import_source");
CREATE INDEX "workflow_runs_imported_at_index" on "workflow_runs" ("imported_at");
CREATE INDEX "workflow_runs_namespace_index" on "workflow_runs" ("namespace");
CREATE INDEX "workflow_runs_namespace_status_quota_idx" on "workflow_runs" ("namespace", "status");
CREATE INDEX "workflow_runs_prom_metrics_queue_idx" on "workflow_runs" ("namespace", "queue");
CREATE INDEX "workflow_runs_sticky_until_index" on "workflow_runs" ("sticky_until");
CREATE INDEX "workflow_runs_sticky_worker_id_index" on "workflow_runs" ("sticky_worker_id");
CREATE INDEX "workflow_runs_workflow_instance_id_index" on "workflow_runs" ("workflow_instance_id");
CREATE UNIQUE INDEX "workflow_runs_workflow_instance_id_run_number_unique" on "workflow_runs" ("workflow_instance_id", "run_number");
CREATE INDEX "workflow_schedules_latest_workflow_instance_id_index" on "workflow_schedules" ("latest_workflow_instance_id");
CREATE INDEX "workflow_schedules_namespace_index" on "workflow_schedules" ("namespace");
CREATE UNIQUE INDEX "workflow_schedules_namespace_schedule_id_unique" on "workflow_schedules" ("namespace", "schedule_id");
CREATE INDEX "workflow_schedules_status_next_fire_at_index" on "workflow_schedules" ("status", "next_fire_at");
CREATE INDEX "workflow_search_attributes_value_bool_index" on "workflow_search_attributes" ("value_bool");
CREATE INDEX "workflow_search_attributes_value_datetime_index" on "workflow_search_attributes" ("value_datetime");
CREATE INDEX "workflow_search_attributes_value_float_index" on "workflow_search_attributes" ("value_float");
CREATE INDEX "workflow_search_attributes_value_int_index" on "workflow_search_attributes" ("value_int");
CREATE INDEX "workflow_search_attributes_value_keyword_index" on "workflow_search_attributes" ("value_keyword");
CREATE INDEX "workflow_search_attributes_workflow_instance_id_index" on "workflow_search_attributes" ("workflow_instance_id");
CREATE INDEX "workflow_search_attributes_workflow_run_id_index" on "workflow_search_attributes" ("workflow_run_id");
CREATE INDEX "workflow_search_attrs_instance_key_type" on "workflow_search_attributes" ("workflow_instance_id", "key", "type");
CREATE INDEX "workflow_search_attrs_key_bool" on "workflow_search_attributes" ("key", "value_bool");
CREATE INDEX "workflow_search_attrs_key_datetime" on "workflow_search_attributes" ("key", "value_datetime");
CREATE INDEX "workflow_search_attrs_key_float" on "workflow_search_attributes" ("key", "value_float");
CREATE INDEX "workflow_search_attrs_key_int" on "workflow_search_attributes" ("key", "value_int");
CREATE INDEX "workflow_search_attrs_key_keyword" on "workflow_search_attributes" ("key", "value_keyword");
CREATE UNIQUE INDEX "workflow_search_attrs_run_key_unique" on "workflow_search_attributes" ("workflow_run_id", "key");
CREATE INDEX "workflow_signal_records_command_sequence_index" on "workflow_signal_records" ("command_sequence");
CREATE INDEX "workflow_signal_records_outcome_index" on "workflow_signal_records" ("outcome");
CREATE INDEX "workflow_signal_records_requested_workflow_run_id_index" on "workflow_signal_records" ("requested_workflow_run_id");
CREATE INDEX "workflow_signal_records_resolved_workflow_run_id_index" on "workflow_signal_records" ("resolved_workflow_run_id");
CREATE INDEX "workflow_signal_records_signal_name_index" on "workflow_signal_records" ("signal_name");
CREATE INDEX "workflow_signal_records_signal_wait_id_index" on "workflow_signal_records" ("signal_wait_id");
CREATE INDEX "workflow_signal_records_status_index" on "workflow_signal_records" ("status");
CREATE UNIQUE INDEX "workflow_signal_records_workflow_command_id_unique" on "workflow_signal_records" ("workflow_command_id");
CREATE INDEX "workflow_signal_records_workflow_instance_id_index" on "workflow_signal_records" ("workflow_instance_id");
CREATE INDEX "workflow_signal_records_workflow_run_id_index" on "workflow_signal_records" ("workflow_run_id");
CREATE INDEX "workflow_signal_records_workflow_sequence_index" on "workflow_signal_records" ("workflow_sequence");
CREATE INDEX "workflow_tasks_dispatch_order_index" on "workflow_tasks" ("queue", "status", "priority", "available_at");
CREATE INDEX "workflow_tasks_fairness_class_index" on "workflow_tasks" ("queue", "status", "fairness_key");
CREATE INDEX "workflow_tasks_namespace_index" on "workflow_tasks" ("namespace");
CREATE INDEX "workflow_tasks_namespace_queue_status_idx" on "workflow_tasks" ("namespace", "queue", "status");
CREATE INDEX "workflow_tasks_prom_metrics_queue_idx" on "workflow_tasks" ("namespace", "queue");
CREATE INDEX "workflow_tasks_status_available_at_index" on "workflow_tasks" ("status", "available_at");
CREATE INDEX "workflow_tasks_sticky_claimed_at_index" on "workflow_tasks" ("sticky_claimed_at");
CREATE INDEX "workflow_tasks_sticky_replay_mode_index" on "workflow_tasks" ("sticky_replay_mode");
CREATE INDEX "workflow_tasks_sticky_until_index" on "workflow_tasks" ("sticky_until");
CREATE INDEX "workflow_tasks_sticky_worker_id_index" on "workflow_tasks" ("sticky_worker_id");
CREATE INDEX "workflow_tasks_workflow_run_id_index" on "workflow_tasks" ("workflow_run_id");
CREATE INDEX "workflow_update_validation_poll_index" on "workflow_update_validation_tasks" ("namespace", "task_queue", "status", "created_at");
CREATE INDEX "workflow_update_validation_tasks_compatibility_index" on "workflow_update_validation_tasks" ("compatibility");
CREATE UNIQUE INDEX "workflow_update_validation_tasks_idempotency_key_unique" on "workflow_update_validation_tasks" ("idempotency_key");
CREATE INDEX "workflow_update_validation_tasks_lease_expires_at_index" on "workflow_update_validation_tasks" ("lease_expires_at");
CREATE INDEX "workflow_update_validation_tasks_lease_owner_index" on "workflow_update_validation_tasks" ("lease_owner");
CREATE INDEX "workflow_update_validation_tasks_namespace_index" on "workflow_update_validation_tasks" ("namespace");
CREATE INDEX "workflow_update_validation_tasks_status_index" on "workflow_update_validation_tasks" ("status");
CREATE INDEX "workflow_update_validation_tasks_task_queue_index" on "workflow_update_validation_tasks" ("task_queue");
CREATE INDEX "workflow_update_validation_tasks_update_name_index" on "workflow_update_validation_tasks" ("update_name");
CREATE INDEX "workflow_update_validation_tasks_workflow_instance_id_index" on "workflow_update_validation_tasks" ("workflow_instance_id");
CREATE INDEX "workflow_update_validation_tasks_workflow_run_id_index" on "workflow_update_validation_tasks" ("workflow_run_id");
CREATE INDEX "workflow_update_validation_tasks_workflow_type_index" on "workflow_update_validation_tasks" ("workflow_type");
CREATE INDEX "workflow_updates_command_sequence_index" on "workflow_updates" ("command_sequence");
CREATE INDEX "workflow_updates_failure_id_index" on "workflow_updates" ("failure_id");
CREATE INDEX "workflow_updates_outcome_index" on "workflow_updates" ("outcome");
CREATE INDEX "workflow_updates_requested_workflow_run_id_index" on "workflow_updates" ("requested_workflow_run_id");
CREATE INDEX "workflow_updates_resolved_workflow_run_id_index" on "workflow_updates" ("resolved_workflow_run_id");
CREATE INDEX "workflow_updates_status_index" on "workflow_updates" ("status");
CREATE INDEX "workflow_updates_update_name_index" on "workflow_updates" ("update_name");
CREATE UNIQUE INDEX "workflow_updates_workflow_command_id_unique" on "workflow_updates" ("workflow_command_id");
CREATE INDEX "workflow_updates_workflow_instance_id_index" on "workflow_updates" ("workflow_instance_id");
CREATE INDEX "workflow_updates_workflow_run_id_index" on "workflow_updates" ("workflow_run_id");
CREATE INDEX "workflow_updates_workflow_sequence_index" on "workflow_updates" ("workflow_sequence");
CREATE INDEX "workflow_worker_compatibility_heartbeats_connection_index" on "workflow_worker_compatibility_heartbeats" ("connection");
CREATE INDEX "workflow_worker_compatibility_heartbeats_expires_at_index" on "workflow_worker_compatibility_heartbeats" ("expires_at");
CREATE INDEX "workflow_worker_compatibility_heartbeats_namespace_index" on "workflow_worker_compatibility_heartbeats" ("namespace");
CREATE INDEX "workflow_worker_compatibility_heartbeats_queue_index" on "workflow_worker_compatibility_heartbeats" ("queue");
CREATE UNIQUE INDEX "workflow_worker_compatibility_heartbeats_scope_unique" on "workflow_worker_compatibility_heartbeats" ("worker_id", "scope_key");
CREATE INDEX "workflow_worker_registrations_namespace_task_queue_status_index" on "workflow_worker_registrations" ("namespace", "task_queue", "status");
CREATE UNIQUE INDEX "workflow_worker_registrations_worker_id_namespace_unique" on "workflow_worker_registrations" ("worker_id", "namespace");
CREATE INDEX "workflow_worker_sessions_namespace_lease_owner_status_index" on "workflow_worker_sessions" ("namespace", "lease_owner", "status");
CREATE INDEX "workflow_worker_sessions_namespace_queue_status_index" on "workflow_worker_sessions" ("namespace", "queue", "status");
CREATE UNIQUE INDEX "workflow_worker_sessions_namespace_session_id_unique" on "workflow_worker_sessions" ("namespace", "session_id");
CREATE INDEX "workflow_worker_sessions_namespace_status_index" on "workflow_worker_sessions" ("namespace", "status");

-- Native bookkeeping uses separate relations; PHP-owned columns stay intact.
CREATE TABLE dw_server_schema (engine TEXT NOT NULL, version INTEGER NOT NULL);
INSERT INTO dw_server_schema VALUES ('rust-development', 2);
CREATE TABLE dw_task_completions (
    task_id TEXT PRIMARY KEY REFERENCES workflow_tasks(id) ON DELETE CASCADE,
    receipt TEXT NOT NULL
);
CREATE TABLE dw_poll_receipts (
    namespace TEXT NOT NULL, worker_id TEXT NOT NULL, kind TEXT NOT NULL,
    request_id TEXT NOT NULL, task_id TEXT NOT NULL REFERENCES workflow_tasks(id) ON DELETE CASCADE,
    attempt INTEGER NOT NULL, response TEXT NOT NULL, expires_at TEXT NOT NULL,
    PRIMARY KEY(namespace,worker_id,kind,request_id)
);
CREATE INDEX dw_workflow_tasks_poll ON workflow_tasks(namespace, queue, task_type, status, available_at);
