SELECT NOW(6) AS captured_at, @@innodb_print_all_deadlocks AS deadlock_logging;
SHOW ENGINE INNODB STATUS;
SELECT THREAD_ID, EVENT_ID, CURRENT_SCHEMA, SQL_TEXT, MYSQL_ERRNO,
       RETURNED_SQLSTATE, MESSAGE_TEXT, TIMER_WAIT, LOCK_TIME, ROWS_AFFECTED
FROM performance_schema.events_statements_history_long
WHERE MYSQL_ERRNO IN (1205, 1213)
ORDER BY THREAD_ID, EVENT_ID
LIMIT 100;
SELECT ENGINE_TRANSACTION_ID, THREAD_ID, OBJECT_SCHEMA, OBJECT_NAME,
       INDEX_NAME, LOCK_TYPE, LOCK_MODE, LOCK_STATUS
FROM performance_schema.data_locks
WHERE OBJECT_SCHEMA = 'durable_workflow'
LIMIT 100;
SELECT * FROM performance_schema.data_lock_waits LIMIT 100;
